// This file is generated by CodeSmith. Do not edit. All edits to this file will be lost. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Xml.Serialization;

//using Indico.BusinessObjects.Util;
//using Indico.BusinessObjects;
using Indico.DAL;


namespace Indico.BusinessObjects
{
    /// <summary>
    /// EmbroideryDetailsViewBO provides the business logic for maintaining Indico.DAL.EmbroideryDetailsView records in the data store.
    /// </summary>
    /// <remarks>
    /// EmbroideryDetailsViewBO provides the business logic for maintaining Indico.DAL.EmbroideryDetailsView records in the data store. 
    /// By default it provides basic Search methods for retrieving Indico.DAL.EmbroideryDetailsView
    /// records using the EmbroideryDetailsView DAL class. Other methods implement atomic chunks of Business Logic according to
    /// the business rules.
    /// </remarks>
    public partial class EmbroideryDetailsViewBO : BusinessObject, IComparable
    {
        #region fields
        private int? _embroidery;
        private DateTime? _embStrikeOffDate;
        private string _jobName;
        private string _distributor;
        private string _client;
        private string _coordinator;
        private string _product;
        private DateTime? _photoRequiredBy;
        private string _creator;
        private DateTime? _createdDate;
        private string _modifier;
        private DateTime? _modifiedDate;
        private string _assign;
        #endregion
        
        #region Properties
        /// <summary></summary>
        public int? Embroidery
        {   get {return _embroidery;}
            set 
            {
                _embroidery = value;
            }
        }
        /// <summary></summary>
        public DateTime? EmbStrikeOffDate
        {   get {return _embStrikeOffDate;}
            set 
            {
                _embStrikeOffDate = value;
            }
        }
        /// <summary></summary>
        public string JobName
        {   get {return _jobName;}
            set 
            {
                _jobName = value;
            }
        }
        /// <summary></summary>
        public string Distributor
        {   get {return _distributor;}
            set 
            {
                _distributor = value;
            }
        }
        /// <summary></summary>
        public string Client
        {   get {return _client;}
            set 
            {
                _client = value;
            }
        }
        /// <summary></summary>
        public string Coordinator
        {   get {return _coordinator;}
            set 
            {
                _coordinator = value;
            }
        }
        /// <summary></summary>
        public string Product
        {   get {return _product;}
            set 
            {
                _product = value;
            }
        }
        /// <summary></summary>
        public DateTime? PhotoRequiredBy
        {   get {return _photoRequiredBy;}
            set 
            {
                _photoRequiredBy = value;
            }
        }
        /// <summary></summary>
        public string Creator
        {   get {return _creator;}
            set 
            {
                _creator = value;
            }
        }
        /// <summary></summary>
        public DateTime? CreatedDate
        {   get {return _createdDate;}
            set 
            {
                _createdDate = value;
            }
        }
        /// <summary></summary>
        public string Modifier
        {   get {return _modifier;}
            set 
            {
                _modifier = value;
            }
        }
        /// <summary></summary>
        public DateTime? ModifiedDate
        {   get {return _modifiedDate;}
            set 
            {
                _modifiedDate = value;
            }
        }
        /// <summary></summary>
        public string Assign
        {   get {return _assign;}
            set 
            {
                _assign = value;
            }
        }
        #endregion
        
        #region Internal Constructors
        /// <summary>
        /// Creates an instance of the EmbroideryDetailsViewBO class using the supplied Indico.DAL.EmbroideryDetailsView. 
        /// </summary>
        /// <param name="obj">a Indico.DAL.EmbroideryDetailsView whose properties will be used to initialise the EmbroideryDetailsViewBO</param>
        internal EmbroideryDetailsViewBO(Indico.DAL.EmbroideryDetailsView obj)
        {
            // set the properties from the Indico.DAL.EmbroideryDetailsView 
            this.Embroidery = obj.Embroidery;
            this.EmbStrikeOffDate = obj.EmbStrikeOffDate;
            this.JobName = obj.JobName;
            this.Distributor = obj.Distributor;
            this.Client = obj.Client;
            this.Coordinator = obj.Coordinator;
            this.Product = obj.Product;
            this.PhotoRequiredBy = obj.PhotoRequiredBy;
            this.Creator = obj.Creator;
            this.CreatedDate = obj.CreatedDate;
            this.Modifier = obj.Modifier;
            this.ModifiedDate = obj.ModifiedDate;
            this.Assign = obj.Assign;
        }
        #endregion
        
        #region Internal utility methods
        internal void SetDAL(Indico.DAL.EmbroideryDetailsView obj, IndicoEntities context)
        {
            // set the Indico.DAL.EmbroideryDetailsView properties
            obj.Embroidery = Convert.ToInt32(Embroidery);
            obj.EmbStrikeOffDate = Convert.ToDateTime(EmbStrikeOffDate);
            obj.JobName = JobName;
            obj.Distributor = Distributor;
            obj.Client = Client;
            obj.Coordinator = Coordinator;
            obj.Product = Product;
            obj.PhotoRequiredBy = Convert.ToDateTime(PhotoRequiredBy);
            obj.Creator = Creator;
            obj.CreatedDate = Convert.ToDateTime(CreatedDate);
            obj.Modifier = Modifier;
            obj.ModifiedDate = Convert.ToDateTime(ModifiedDate);
            obj.Assign = Assign;
        }
        
        internal void SetBO(Indico.DAL.EmbroideryDetailsView obj)
        {
            // set the Indico.BusinessObjects.EmbroideryDetailsViewBO properties    
            this.Embroidery = obj.Embroidery;
            this.EmbStrikeOffDate = obj.EmbStrikeOffDate;
            this.JobName = obj.JobName;
            this.Distributor = obj.Distributor;
            this.Client = obj.Client;
            this.Coordinator = obj.Coordinator;
            this.Product = obj.Product;
            this.PhotoRequiredBy = obj.PhotoRequiredBy;
            this.Creator = obj.Creator;
            this.CreatedDate = obj.CreatedDate;
            this.Modifier = obj.Modifier;
            this.ModifiedDate = obj.ModifiedDate;
            this.Assign = obj.Assign;
        }
        
        internal void SetBO(Indico.BusinessObjects.EmbroideryDetailsViewBO obj)
        {
            // set this Indico.BusinessObjects.EmbroideryDetailsViewBO properties
            this.Embroidery = obj.Embroidery;
            this.EmbStrikeOffDate = obj.EmbStrikeOffDate;
            this.JobName = obj.JobName;
            this.Distributor = obj.Distributor;
            this.Client = obj.Client;
            this.Coordinator = obj.Coordinator;
            this.Product = obj.Product;
            this.PhotoRequiredBy = obj.PhotoRequiredBy;
            this.Creator = obj.Creator;
            this.CreatedDate = obj.CreatedDate;
            this.Modifier = obj.Modifier;
            this.ModifiedDate = obj.ModifiedDate;
            this.Assign = obj.Assign;
        }
        
        private static List<Indico.BusinessObjects.EmbroideryDetailsViewBO> IQueryableToList(IQueryable<Indico.DAL.EmbroideryDetailsView> oQuery)
        {
            List<Indico.DAL.EmbroideryDetailsView> oList = oQuery.ToList();
            List<Indico.BusinessObjects.EmbroideryDetailsViewBO> rList = new List<Indico.BusinessObjects.EmbroideryDetailsViewBO>(oList.Count);
            foreach (Indico.DAL.EmbroideryDetailsView o in oList)
            {
                Indico.BusinessObjects.EmbroideryDetailsViewBO obj = new Indico.BusinessObjects.EmbroideryDetailsViewBO(o);
                rList.Add(obj);
            }
            return rList;
        }
        #endregion
        
        #region BusinessObject methods
        
        #region GetAllObject
        public static List<Indico.BusinessObjects.EmbroideryDetailsViewBO> GetAllObject()
        {
            return GetAllObject(0, 0);
        }
        public static List<Indico.BusinessObjects.EmbroideryDetailsViewBO> GetAllObject(int maximumRows)
        {
            return GetAllObject(maximumRows, 0);
        }
        public static List<Indico.BusinessObjects.EmbroideryDetailsViewBO> GetAllObject(int maximumRows, int startIndex)
        {
            return GetAllObject(maximumRows, startIndex, null, false);
        }
        public static List<Indico.BusinessObjects.EmbroideryDetailsViewBO> GetAllObject(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.EmbroideryDetailsView> oQuery =
                (from o in context.EmbroideryDetailsView
                 orderby o.Embroidery
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.Embroidery).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.EmbroideryDetailsViewBO> embroiderydetailsviews = IQueryableToList(oQuery);
            context.Dispose();
            return embroiderydetailsviews;
        }
        #endregion
        
        #region SearchObjects
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchObjects()
        {
            return SearchObjects(0,0);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchObjects(int maximumRows)
        {
            return SearchObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchObjects(int maximumRows, int startIndex)
        {
            return SearchObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.EmbroideryDetailsView> oQuery =
                (from o in context.EmbroideryDetailsView
                 where
                    (this.Embroidery == null || this.Embroidery == o.Embroidery) &&
                    (this.EmbStrikeOffDate == null || this.EmbStrikeOffDate == o.EmbStrikeOffDate) &&
                    (this.JobName == null || this.JobName == o.JobName) &&
                    (this.Distributor == null || this.Distributor == o.Distributor) &&
                    (this.Client == null || this.Client == o.Client) &&
                    (this.Coordinator == null || this.Coordinator == o.Coordinator) &&
                    (this.Product == null || this.Product == o.Product) &&
                    (this.PhotoRequiredBy == null || this.PhotoRequiredBy == o.PhotoRequiredBy) &&
                    (this.Creator == null || this.Creator == o.Creator) &&
                    (this.CreatedDate == null || this.CreatedDate == o.CreatedDate) &&
                    (this.Modifier == null || this.Modifier == o.Modifier) &&
                    (this.ModifiedDate == null || this.ModifiedDate == o.ModifiedDate) &&
                    (this.Assign == null || this.Assign == o.Assign) 
                 orderby o.Embroidery
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.Embroidery).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.EmbroideryDetailsViewBO> embroiderydetailsviews = IQueryableToList(oQuery);
            context.Dispose();
            return embroiderydetailsviews;
        }
        
        public int SearchObjectsCount()
        {
            IndicoEntities context = new IndicoEntities();
            return (from o in context.EmbroideryDetailsView
                 where
                    (this.Embroidery == null || this.Embroidery == o.Embroidery) &&
                    (this.EmbStrikeOffDate == null || this.EmbStrikeOffDate == o.EmbStrikeOffDate) &&
                    (this.JobName == null || this.JobName == o.JobName) &&
                    (this.Distributor == null || this.Distributor == o.Distributor) &&
                    (this.Client == null || this.Client == o.Client) &&
                    (this.Coordinator == null || this.Coordinator == o.Coordinator) &&
                    (this.Product == null || this.Product == o.Product) &&
                    (this.PhotoRequiredBy == null || this.PhotoRequiredBy == o.PhotoRequiredBy) &&
                    (this.Creator == null || this.Creator == o.Creator) &&
                    (this.CreatedDate == null || this.CreatedDate == o.CreatedDate) &&
                    (this.Modifier == null || this.Modifier == o.Modifier) &&
                    (this.ModifiedDate == null || this.ModifiedDate == o.ModifiedDate) &&
                    (this.Assign == null || this.Assign == o.Assign) 
                 orderby o.Embroidery
                 select o).Count();
        }
        #endregion
        
        #region SearchObjectsLikeAnd
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeAndObjects()
        {
            return SearchLikeAndObjects(0);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeAndObjects(int maximumRows)
        {
            return SearchLikeAndObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeAndObjects(int maximumRows, int startIndex)
        {
            return SearchLikeAndObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeAndObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.EmbroideryDetailsView> oQuery =
                (from o in context.EmbroideryDetailsView
                 where
                    (this.Embroidery == null || o.Embroidery == this.Embroidery) &&
                    (this.EmbStrikeOffDate == null || o.EmbStrikeOffDate == this.EmbStrikeOffDate) &&
                    (this.JobName == null || o.JobName.Contains(this.JobName)) &&
                    (this.Distributor == null || o.Distributor.Contains(this.Distributor)) &&
                    (this.Client == null || o.Client.Contains(this.Client)) &&
                    (this.Coordinator == null || o.Coordinator.Contains(this.Coordinator)) &&
                    (this.Product == null || o.Product.Contains(this.Product)) &&
                    (this.PhotoRequiredBy == null || o.PhotoRequiredBy == this.PhotoRequiredBy) &&
                    (this.Creator == null || o.Creator.Contains(this.Creator)) &&
                    (this.CreatedDate == null || o.CreatedDate == this.CreatedDate) &&
                    (this.Modifier == null || o.Modifier.Contains(this.Modifier)) &&
                    (this.ModifiedDate == null || o.ModifiedDate == this.ModifiedDate) &&
                    (this.Assign == null || o.Assign.Contains(this.Assign)) 
                 orderby o.Embroidery
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.Embroidery).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.EmbroideryDetailsViewBO> embroiderydetailsviews = IQueryableToList(oQuery);
            context.Dispose();
            return embroiderydetailsviews;
        }
        
        public int SearchLikeAndObjectsCount()
        {
            IndicoEntities context = new IndicoEntities();
            return (from o in context.EmbroideryDetailsView
                 where
                    (this.Embroidery == null || o.Embroidery == this.Embroidery) &&
                    (this.EmbStrikeOffDate == null || o.EmbStrikeOffDate == this.EmbStrikeOffDate) &&
                    (this.JobName == null || o.JobName.Contains(this.JobName)) &&
                    (this.Distributor == null || o.Distributor.Contains(this.Distributor)) &&
                    (this.Client == null || o.Client.Contains(this.Client)) &&
                    (this.Coordinator == null || o.Coordinator.Contains(this.Coordinator)) &&
                    (this.Product == null || o.Product.Contains(this.Product)) &&
                    (this.PhotoRequiredBy == null || o.PhotoRequiredBy == this.PhotoRequiredBy) &&
                    (this.Creator == null || o.Creator.Contains(this.Creator)) &&
                    (this.CreatedDate == null || o.CreatedDate == this.CreatedDate) &&
                    (this.Modifier == null || o.Modifier.Contains(this.Modifier)) &&
                    (this.ModifiedDate == null || o.ModifiedDate == this.ModifiedDate) &&
                    (this.Assign == null || o.Assign.Contains(this.Assign)) 
                 orderby o.Embroidery
                 select o).Count();
            
        }
        
        #endregion
        
        #region SearchObjectsLikeOr
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeOrObjects()
        {
            return SearchLikeOrObjects(0);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeOrObjects(int maximumRows)
        {
            return SearchLikeOrObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeOrObjects(int maximumRows, int startIndex)
        {
            return SearchLikeOrObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.EmbroideryDetailsViewBO> SearchLikeOrObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.EmbroideryDetailsView> oQuery =
                (from o in context.EmbroideryDetailsView
                 where
                    (this.Embroidery == null || this.Embroidery == o.Embroidery) && 
                    (this.EmbStrikeOffDate == null || this.EmbStrikeOffDate == o.EmbStrikeOffDate) && 
                    (this.PhotoRequiredBy == null || this.PhotoRequiredBy == o.PhotoRequiredBy) && 
                    (this.CreatedDate == null || this.CreatedDate == o.CreatedDate) && 
                    (this.ModifiedDate == null || this.ModifiedDate == o.ModifiedDate) && 
                    ((o.JobName.Contains(this.JobName)) ||
                    (o.Distributor.Contains(this.Distributor)) ||
                    (o.Client.Contains(this.Client)) ||
                    (o.Coordinator.Contains(this.Coordinator)) ||
                    (o.Product.Contains(this.Product)) ||
                    (o.Creator.Contains(this.Creator)) ||
                    (o.Modifier.Contains(this.Modifier)) ||
                    (o.Assign.Contains(this.Assign)) ||
                    (this.JobName == null && this.Distributor == null && this.Client == null && this.Coordinator == null && this.Product == null && this.Creator == null && this.Modifier == null && this.Assign == null ))
                 orderby o.Embroidery
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.Embroidery).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.EmbroideryDetailsViewBO> embroiderydetailsviews = IQueryableToList(oQuery);
            context.Dispose();
            return embroiderydetailsviews;
        }
        
        public int SearchLikeOrObjectsCount()
        {
            IndicoEntities context = new IndicoEntities();
            return (from o in context.EmbroideryDetailsView
                 where
                    (this.Embroidery == null || this.Embroidery == o.Embroidery) && 
                    (this.EmbStrikeOffDate == null || this.EmbStrikeOffDate == o.EmbStrikeOffDate) && 
                    (this.PhotoRequiredBy == null || this.PhotoRequiredBy == o.PhotoRequiredBy) && 
                    (this.CreatedDate == null || this.CreatedDate == o.CreatedDate) && 
                    (this.ModifiedDate == null || this.ModifiedDate == o.ModifiedDate) && 
                    ((o.JobName.Contains(this.JobName)) ||
                    (o.Distributor.Contains(this.Distributor)) ||
                    (o.Client.Contains(this.Client)) ||
                    (o.Coordinator.Contains(this.Coordinator)) ||
                    (o.Product.Contains(this.Product)) ||
                    (o.Creator.Contains(this.Creator)) ||
                    (o.Modifier.Contains(this.Modifier)) ||
                    (o.Assign.Contains(this.Assign)) ||
                    (this.JobName == null && this.Distributor == null && this.Client == null && this.Coordinator == null && this.Product == null && this.Creator == null && this.Modifier == null && this.Assign == null ))
                 orderby o.Embroidery
                 select o).Count();
            
        }
        #endregion
        
        #region Serialization methods
        /// <summary>
        /// Serializes the Indico.BusinessObjects.EmbroideryDetailsViewBO to an XML representation
        /// </summary>
        /// <returns>a XML string serialized representation</returns>
        public string SerializeObject()
        {
            string strReturn = "";

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();

            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            x.Serialize(objStream, this);

            System.Text.Encoding encoding = System.Text.Encoding.UTF8;
            // Read string from binary file with UTF8 encoding
            strReturn = encoding.GetString(objStream.GetBuffer());

            objStream.Close();
            return strReturn;

        }

        /// <summary>
        /// Deserializes Indico.BusinessObjects.EmbroideryDetailsViewBO object from an XML representation
        /// </summary>
        /// <param name="strXML">a XML string serialized representation</param>
        public Indico.BusinessObjects.EmbroideryDetailsViewBO DeserializeObject(string strXML)
        {
            Indico.BusinessObjects.EmbroideryDetailsViewBO objTemp = null;
            System.Xml.XmlDocument objXML = new System.Xml.XmlDocument();

            objXML.LoadXml(strXML);
            System.Text.Encoding encoding = System.Text.Encoding.UTF8;

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();
            byte[] b = encoding.GetBytes(objXML.OuterXml);

            objStream.Write(b, 0, (int)b.Length);
            objStream.Position = 0;
            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            objTemp = (Indico.BusinessObjects.EmbroideryDetailsViewBO)x.Deserialize(objStream);
            objStream.Close();
            return objTemp;
        }

        /// <summary>
        /// Returns a simple XML representation of Indico.BusinessObjects.EmbroideryDetailsViewBO object in an XmlElement
        /// </summary>
        /// <returns>An XML snippet representing the object</returns>
        public string ToXmlString()
        {
            // MW TODO - implement this better.
            return SerializeObject();
        }
        #endregion
        
        #region IComparable Members

        public int CompareTo(object obj)
        {
            if (!(obj is Indico.BusinessObjects.EmbroideryDetailsViewBO))
                return 1;
            Indico.BusinessObjects.EmbroideryDetailsViewBOComparer c = new Indico.BusinessObjects.EmbroideryDetailsViewBOComparer();
            return c.Compare(this, obj as Indico.BusinessObjects.EmbroideryDetailsViewBO);
        }

        #endregion
        #endregion
    }
    
    #region EmbroideryDetailsViewBOComparer
    public class EmbroideryDetailsViewBOComparer : IComparer<Indico.BusinessObjects.EmbroideryDetailsViewBO>
    {
        private string propertyToCompareName;
        public EmbroideryDetailsViewBOComparer(string propertyToCompare)
        {
            PropertyInfo p = typeof(Indico.BusinessObjects.EmbroideryDetailsViewBO).GetProperty(propertyToCompare);
            if (p == null)
                throw new ArgumentException("is not a public property of Indico.BusinessObjects.EmbroideryDetailsViewBO", "propertyToCompare");
            this.propertyToCompareName = propertyToCompare;
        }
        
        public EmbroideryDetailsViewBOComparer()
        {
        
        }

        #region IComparer<Indico.BusinessObjects.EmbroideryDetailsViewBO> Members
        public int Compare(Indico.BusinessObjects.EmbroideryDetailsViewBO x, Indico.BusinessObjects.EmbroideryDetailsViewBO y)
        {
            if (propertyToCompareName != null)
            {
                PropertyInfo p = typeof(Indico.BusinessObjects.EmbroideryDetailsViewBO).GetProperty(propertyToCompareName);
                return compare(p, x, y);
            }
            else
            {
                PropertyInfo[] arrP = typeof(Indico.BusinessObjects.EmbroideryDetailsViewBO).GetProperties();
                foreach (PropertyInfo p in arrP)
                {
                    int v = compare(p, x, y);
                    if (v != 0)
                        return v;
                }
                return 0;
            }
        }

        private int compare(PropertyInfo p, Indico.BusinessObjects.EmbroideryDetailsViewBO x, Indico.BusinessObjects.EmbroideryDetailsViewBO y)
        {
            object xVal = p.GetValue(x, null);
            object yVal = p.GetValue(y, null);

            if (xVal == null)
            {
                if (yVal == null)
                    return 0;
                else
                    return -1; // x is null, y is not, y is greater
            }
            else
            {
                if (y == null)
                    return 1; // x non null, y is null, x is greater
                else if (xVal is string)
                {
                    return StringComparer.OrdinalIgnoreCase.Compare(xVal, yVal);
                }
                else if (xVal is IComparable)
                {
                    return ((IComparable)xVal).CompareTo((IComparable)yVal);
                }
                else
                    throw new ArgumentException
                        ("is not string or valuetype that implements IComparable", "propertyToCompare");

            }
        }

        #endregion
    }
    #endregion
}
