// This file is generated by CodeSmith. Do not edit. All edits to this file will be lost. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Xml.Serialization;

using Indico.DAL;

//namespace Indico.BusinessObjects
namespace Indico.BusinessObjects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ImageBO : BusinessObject, IComparable
    {
        #region fields
        #region Scalar Fields
        private int id;
        private string _extension;
        private string _filename;
        private bool _isHero;
        private int _size;
        private int _visualLayout;
        #endregion
        
        #region Foreign Key fields
        [NonSerialized][XmlIgnoreAttribute]
        private Indico.BusinessObjects.VisualLayoutBO _objVisualLayout;
        #endregion
        
        #region Foreign Table Foreign Key fields
        #endregion
        
        #region Other fields
        
        private Indico.DAL.Image _objDAL = null;
        private bool _doNotUpdateDALObject = false;
        
        #endregion
        
        #endregion
        
        #region Properties
        /// <summary>The Primary Key for this object</summary>
        public int ID
        {   get {return id;}
            set 
            {
                OnIDChanging(value);
                id = value;
                OnIDChanged();
            }
        }
        
        /// <summary>The file extension of the image. The maximum length of this property is 10.</summary>
        public string Extension
        {   
            get {return _extension;}
            set 
            {
                OnExtensionChanging(value);
                _extension = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Extension = value;
                }
                OnExtensionChanged();
            }
        }
        /// <summary>The filename of the image. The maximum length of this property is 255.</summary>
        public string Filename
        {   
            get {return _filename;}
            set 
            {
                OnFilenameChanging(value);
                _filename = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Filename = value;
                }
                OnFilenameChanged();
            }
        }
        /// <summary>Is this is the hero image?.</summary>
        public bool IsHero
        {   
            get {return _isHero;}
            set 
            {
                OnIsHeroChanging(value);
                _isHero = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.IsHero = value;
                }
                OnIsHeroChanged();
            }
        }
        /// <summary>The size in bytes of the image.</summary>
        public int Size
        {   
            get {return _size;}
            set 
            {
                OnSizeChanging(value);
                _size = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Size = value;
                }
                OnSizeChanged();
            }
        }
        /// <summary>The ID of the Visual layout.</summary>
        public int VisualLayout
        {   
            get {return _visualLayout;}
            set 
            {
                OnVisualLayoutChanging(value);
                _visualLayout = value;
                if (!this._doNotUpdateDALObject && this._context != null && this.ObjDAL != null && ((int)value != 0))
                {
                    this.ObjDAL.VisualLayout = (from o in this._context.Context.VisualLayout
                                           where o.ID == (int)value
                                           select o).ToList<Indico.DAL.VisualLayout>()[0];
                }
                else if (!this._doNotUpdateDALObject && this._context != null && this.ObjDAL != null && (int)value == 0)
                    this.ObjDAL.VisualLayout = null;
                OnVisualLayoutChanged();
            }
        }
        
        internal Indico.DAL.Image ObjDAL
        {
            get 
            {
                if (_objDAL == null && base._createDAL)
                {
                    _objDAL = this.SetDAL(this.Context.Context);
                    this.ObjDAL.PropertyChanged += new System.ComponentModel.PropertyChangedEventHandler(obj_PropertyChanged);
                }

                return _objDAL;
            }
            set 
            {
                _objDAL = value;
            }
        }
        
        #endregion
        
        #region Non-scalar Properties
        
        #region Foreign Key Objects
        ///<summary>The VisualLayoutBO object identified by the value of VisualLayout</summary>
        [XmlIgnoreAttribute]
        public Indico.BusinessObjects.VisualLayoutBO objVisualLayout
        {
            get
            {
                if ( _visualLayout > 0 && _objVisualLayout == null)
                {
                        if (this._context == null)
                        {
                            _objVisualLayout = new Indico.BusinessObjects.VisualLayoutBO();
                        }
                        else
                        {
                            _objVisualLayout = new Indico.BusinessObjects.VisualLayoutBO(ref this._context);
                        }
                        _objVisualLayout.ID = _visualLayout;
                        _objVisualLayout.GetObject(); 
                }
                return _objVisualLayout;
            }
            set
            { 
                _objVisualLayout = value;
                _visualLayout = _objVisualLayout.ID;
            }
        }
        #endregion
        
        #region Foreign Object Foreign Key Collections
        #endregion
        
        #endregion
        
        #region Internal Constructors
        /// <summary>
        /// Creates an instance of the ImageBO class using the supplied Indico.DAL.Image. 
        /// </summary>
        /// <param name="obj">a Indico.DAL.Image whose properties will be used to initialise the ImageBO</param>
        internal ImageBO(Indico.DAL.Image obj, ref IndicoContext context)
        {
            this._doNotUpdateDALObject = true;
            
            this.Context = context;
        
            // set the properties from the Indico.DAL.Image 
            this.ID = obj.ID;
            
            this.Extension = obj.Extension;
            this.Filename = obj.Filename;
            this.IsHero = obj.IsHero;
            this.Size = obj.Size;
            this.VisualLayout = (obj.VisualLayoutReference.EntityKey != null && obj.VisualLayoutReference.EntityKey.EntityKeyValues.Count() > 0)
                ? (int)((System.Data.EntityKeyMember)obj.VisualLayoutReference.EntityKey.EntityKeyValues.GetValue(0)).Value
                : 0;
            
            this._doNotUpdateDALObject = false;
        }
        #endregion
        
        #region Internal utility methods
        internal Indico.DAL.Image SetDAL(IndicoEntities context)
        {
            this._doNotUpdateDALObject = true;
        
            // set the Indico.DAL.Image properties
            Indico.DAL.Image obj = new Indico.DAL.Image();
            
            if (this.ID > 0)
            {
                obj = context.Image.FirstOrDefault<Image>(o => o.ID == this.ID);
            }
            
            obj.Extension = this.Extension;
            obj.Filename = this.Filename;
            obj.IsHero = this.IsHero;
            obj.Size = this.Size;
            
            if (this.VisualLayout > 0) obj.VisualLayout = context.VisualLayout.FirstOrDefault(o => o.ID == this.VisualLayout);
            
            
            this._doNotUpdateDALObject = false;
            
            return obj;
        }
        
        internal void SetBO(System.Data.Objects.DataClasses.EntityObject eObj)
        {
            this._doNotUpdateDALObject = true;
            
            // Check the received type
            if (eObj.GetType() != typeof(Indico.DAL.Image))
            {
                throw new FormatException("Received wrong parameter type...");
            }

            Indico.DAL.Image obj = (Indico.DAL.Image)eObj;
            
            // set the Indico.BusinessObjects.ImageBO properties
            this.ID = obj.ID;
            
            this.Extension = obj.Extension;
            this.Filename = obj.Filename;
            this.IsHero = obj.IsHero;
            this.Size = obj.Size;
            
            this.VisualLayout = (obj.VisualLayoutReference.EntityKey != null && obj.VisualLayoutReference.EntityKey.EntityKeyValues.Count() > 0)
                ? (int)((System.Data.EntityKeyMember)obj.VisualLayoutReference.EntityKey.EntityKeyValues.GetValue(0)).Value
                : 0;
            
            this._doNotUpdateDALObject = false;
        }
        
        internal void SetBO(Indico.BusinessObjects.ImageBO obj)
        {
            this._doNotUpdateDALObject = true;
            
            // set this Indico.BusinessObjects.ImageBO properties
            this.ID = obj.ID;
            
            this.Extension = obj.Extension;
            this.Filename = obj.Filename;
            this.IsHero = obj.IsHero;
            this.Size = obj.Size;
            this.VisualLayout = obj.VisualLayout;
            
            this._doNotUpdateDALObject = false;
        }
        
        internal List<Indico.BusinessObjects.ImageBO> IQueryableToList(IQueryable<Indico.DAL.Image> oQuery)
        {
            List<Indico.DAL.Image> oList = oQuery.ToList();
            List<Indico.BusinessObjects.ImageBO> rList = new List<Indico.BusinessObjects.ImageBO>(oList.Count);
            foreach (Indico.DAL.Image o in oList)
            {
                Indico.BusinessObjects.ImageBO obj = new Indico.BusinessObjects.ImageBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal List<Indico.BusinessObjects.ImageBO> ToList(IEnumerable<Indico.DAL.Image> oQuery)
        {
            List<Indico.DAL.Image> oList = oQuery.ToList();
            List<Indico.BusinessObjects.ImageBO> rList = new List<Indico.BusinessObjects.ImageBO>(oList.Count);
            foreach (Indico.DAL.Image o in oList)
            {
                Indico.BusinessObjects.ImageBO obj = new Indico.BusinessObjects.ImageBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal static List<Indico.DAL.Image> ToEntityList(List<ImageBO> bos, IndicoEntities context)
        {
            // build a List of Image entities from the business objects
            List<Int32> ids = (from o in bos
                                   select o.ID).ToList<Int32>();

            return (context.Image.Count() == 0) ? new List<Indico.DAL.Image>() : (context.Image.Where(BuildContainsExpression<Image, int>(e => e.ID, ids)))
                .ToList<Indico.DAL.Image>();
        }
        
        internal static System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.Image> ToEntityCollection(List<ImageBO> bos, IndicoEntities context)
        {
            // build an EntityCollection of Image entities from the business objects
            List<Int32> ids = (from o in bos
                               select o.ID).ToList<Int32>();

            List<Indico.DAL.Image> el = (context.Image.Count() == 0) ? new List<Indico.DAL.Image>() : 
                context.Image.Where(BuildContainsExpression<Image, int>(e => e.ID, ids))
                .ToList<Indico.DAL.Image>();
                
            System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.Image> ec 
                = new System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.Image>();
                
            foreach (Indico.DAL.Image r in el) 
            {
                ec.Add(r);
            }
            return ec;
        }

        internal Indico.DAL.Image ToEntity(IndicoEntities context)
        {
            return (from o in context.Image
                    where o.ID == this.ID
                    select o).FirstOrDefault();
        }
        #endregion
        
        #region BusinessObject methods
        
        #region Add Object
        
        public void Add()
        {
            if (this.Context != null)
            {
                this.Context.Context.AddToImage(this.ObjDAL);
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.Image obj = this.SetDAL(objContext.Context);
                objContext.Context.AddToImage(obj);
                objContext.SaveChanges();
                objContext.Dispose(); 
            }
        }
        
        #endregion
        
        #region Delete Object
        
        public void Delete()
        {
            if (this.Context != null)
            {
                if (this.ObjDAL != null && this.ObjDAL.EntityKey != null)
                {
                    if (this.ObjDAL.EntityState == System.Data.EntityState.Detached)
                    {
                        this.Context.Context.Attach(this.ObjDAL);
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                    else
                    {
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                }
                else
                {
                    Indico.DAL.Image obj = this.SetDAL(this.Context.Context);
                    this.Context.Context.DeleteObject(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.Image obj = this.SetDAL(objContext.Context);
                this.Context.Context.DeleteObject(obj);
                objContext.Context.SaveChanges();
                objContext.Dispose();
            }
        }
        
        #endregion
        
        #region Get Single Object
        
        public bool GetObject()
        {
            return GetObject(true);
        }
        public bool GetObject(bool blnCache)
        {
            Indico.BusinessObjects.ImageBO data = null;
            
            if (blnCache)
            {
                data = this.GetFromCache(this.ID) as Indico.BusinessObjects.ImageBO; 
            }

            if (data != null)
            {
                SetBO(data);
            }
            else
            {
                try
                {
                    IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
                    IQueryable<Indico.DAL.Image> oQuery =
                        from o in context.Image
                        where o.ID == this.ID
                        select o;

                    List<Indico.DAL.Image> oList = oQuery.ToList();
                    if (oList.Count != 1)
                        return false;
                    else
                    {
                        SetBO(oList[0]);
                        this.Cache();
                    }
                    
                    if (this.Context == null)
                    {
                        context.Dispose();
                    }
                }
                catch (System.Exception e)
                {
                    throw new IndicoException(String.Format(System.Globalization.CultureInfo.InvariantCulture, ResourceManager.GetString("Could not Retrieve a {0} from the data store", System.Globalization.CultureInfo.CurrentCulture), this.ToString()), e, IndicoException.Severities.USER, IndicoException.ERRNO.INT_ERR_BO_SELECT_FAIL);
                }
            }
            return true;
        }
        #endregion
        
        #region GetAllObject
        public List<Indico.BusinessObjects.ImageBO> GetAllObject()
        {
            return GetAllObject(0, 0);
        }
        public List<Indico.BusinessObjects.ImageBO> GetAllObject(int maximumRows)
        {
            return GetAllObject(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.ImageBO> GetAllObject(int maximumRows, int startIndex)
        {
            return GetAllObject(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.ImageBO> GetAllObject(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.Image> oQuery =
                (from o in context.Image
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.ImageBO> images = IQueryableToList(oQuery);
            context.Dispose();
            return images;
        }
        #endregion
        
        #region SearchObjects
        public List<Indico.BusinessObjects.ImageBO> SearchObjects()
        {
            return SearchObjects(0,0);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchObjects(int maximumRows)
        {
            return SearchObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchObjects(int maximumRows, int startIndex)
        {
            return SearchObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.Image> oQuery =
                (from o in context.Image
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.VisualLayout == 0 || this.VisualLayout == o.VisualLayout.ID) &&
                    (this.Size == 0 || this.Size == o.Size) &&
                    (this.Filename == null || this.Filename == o.Filename) &&
                    (this.Extension == null || this.Extension == o.Extension) &&
                    (this.IsHero == false || this.IsHero == o.IsHero) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.ImageBO> images = IQueryableToList(oQuery);
            
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return images;
        }
        
        public int SearchObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.Image
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.VisualLayout == 0 || this.VisualLayout == o.VisualLayout.ID) &&
                    (this.Size == 0 || this.Size == o.Size) &&
                    (this.Filename == null || this.Filename == o.Filename) &&
                    (this.Extension == null || this.Extension == o.Extension) &&
                    (this.IsHero == false || this.IsHero == o.IsHero) 
                 orderby o.ID
                 select o).Count();
        }
        #endregion
        
        #region SearchObjectsLikeAnd
        public List<Indico.BusinessObjects.ImageBO> SearchLikeAndObjects()
        {
            return SearchLikeAndObjects(0);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchLikeAndObjects(int maximumRows)
        {
            return SearchLikeAndObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchLikeAndObjects(int maximumRows, int startIndex)
        {
            return SearchLikeAndObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchLikeAndObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.Image> oQuery =
                (from o in context.Image
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.VisualLayout == 0 || o.VisualLayout.ID == this.VisualLayout) &&
                    (this.Size == 0 || o.Size == this.Size) &&
                    (this.Filename == null || o.Filename.Contains(this.Filename)) &&
                    (this.Extension == null || o.Extension.Contains(this.Extension)) &&
                    (this.IsHero == false || o.IsHero == this.IsHero) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.ImageBO> images = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return images;
        }
        
        public int SearchLikeAndObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.Image
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.VisualLayout == 0 || o.VisualLayout.ID == this.VisualLayout) &&
                    (this.Size == 0 || o.Size == this.Size) &&
                    (this.Filename == null || o.Filename.Contains(this.Filename)) &&
                    (this.Extension == null || o.Extension.Contains(this.Extension)) &&
                    (this.IsHero == false || o.IsHero == this.IsHero) 
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region SearchObjectsLikeOr
        public List<Indico.BusinessObjects.ImageBO> SearchLikeOrObjects()
        {
            return SearchLikeOrObjects(0);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchLikeOrObjects(int maximumRows)
        {
            return SearchLikeOrObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchLikeOrObjects(int maximumRows, int startIndex)
        {
            return SearchLikeOrObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.ImageBO> SearchLikeOrObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.Image> oQuery =
                (from o in context.Image
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    (this.VisualLayout == 0 || this.VisualLayout == o.VisualLayout.ID) && 
                    (this.Size == 0 || this.Size == o.Size) && 
                    (this.IsHero == false || this.IsHero == o.IsHero) && 
                    ((o.Filename.Contains(this.Filename)) ||
                    (o.Extension.Contains(this.Extension)) ||
                    (this.Filename == null && this.Extension == null ))
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.ImageBO> images = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return images;
        }
        
        public int SearchLikeOrObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.Image
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    (this.VisualLayout == 0 || this.VisualLayout == o.VisualLayout.ID) && 
                    (this.Size == 0 || this.Size == o.Size) && 
                    (this.IsHero == false || this.IsHero == o.IsHero) && 
                    ((o.Filename.Contains(this.Filename)) ||
                    (o.Extension.Contains(this.Extension)) ||
                    (this.Filename == null && this.Extension == null ))
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region Serialization methods
        /// <summary>
        /// Serializes the Indico.BusinessObjects.ImageBO to an XML representation
        /// </summary>
        /// <returns>a XML string serialized representation</returns>
        public string SerializeObject()
        {
            string strReturn = "";

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();

            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            x.Serialize(objStream, this);

            System.Text.Encoding encoding = System.Text.Encoding.UTF8;
            // Read string from binary file with UTF8 encoding
            strReturn = encoding.GetString(objStream.GetBuffer());

            objStream.Close();
            return strReturn;

        }

        /// <summary>
        /// Deserializes Indico.BusinessObjects.ImageBO object from an XML representation
        /// </summary>
        /// <param name="strXML">a XML string serialized representation</param>
        public Indico.BusinessObjects.ImageBO DeserializeObject(string strXML)
        {
            Indico.BusinessObjects.ImageBO objTemp = null;
            System.Xml.XmlDocument objXML = new System.Xml.XmlDocument();

            objXML.LoadXml(strXML);
            System.Text.Encoding encoding = System.Text.Encoding.UTF8;

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();
            byte[] b = encoding.GetBytes(objXML.OuterXml);

            objStream.Write(b, 0, (int)b.Length);
            objStream.Position = 0;
            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            objTemp = (Indico.BusinessObjects.ImageBO)x.Deserialize(objStream);
            objStream.Close();
            return objTemp;
        }

        /// <summary>
        /// Returns a simple XML representation of Indico.BusinessObjects.ImageBO object in an XmlElement
        /// </summary>
        /// <returns>An XML snippet representing the object</returns>
        public string ToXmlString()
        {
            // MW TODO - implement this better.
            return SerializeObject();
        }
        #endregion
        
        #region OnPropertyChange Methods
        partial void OnIDChanged()
        {
            OnImageBOIDChanged();
        }
        
        partial void OnIDChanging(int value)
        {
            if (value < 0)
            {
                throw new Exception(String.Format("ImageBO.ID must be more than or equal to 0. The supplied value was {0}.", value));
            }
            OnImageBOIDChanging(value);
        }
        partial void OnIDChanged();
        partial void OnIDChanging(int value);
        partial void OnImageBOIDChanged();
        partial void OnImageBOIDChanging(int value);
        
        partial void OnVisualLayoutChanged()
        {
            OnImageBOVisualLayoutChanged();
        }
        
        partial void OnVisualLayoutChanging(int value)
        {
            if (value < 0)
            {
                throw new Exception(String.Format("ImageBO.VisualLayout must be more than or equal to 0. The supplied value was {0}.", value));
            }
            OnImageBOVisualLayoutChanging(value);
        }
        partial void OnVisualLayoutChanged();
        partial void OnVisualLayoutChanging(int value);
        partial void OnImageBOVisualLayoutChanged();
        partial void OnImageBOVisualLayoutChanging(int value);
        
        partial void OnSizeChanged()
        {
            OnImageBOSizeChanged();
        }
        
        partial void OnSizeChanging(int value)
        {
            OnImageBOSizeChanging(value);
        }
        partial void OnSizeChanged();
        partial void OnSizeChanging(int value);
        partial void OnImageBOSizeChanged();
        partial void OnImageBOSizeChanging(int value);
        
        partial void OnFilenameChanged()
        {
            OnImageBOFilenameChanged();
        }
        
        partial void OnFilenameChanging(string value)
        {
            if (value != null && value.Length > 255)
            {
                throw new Exception(String.Format("ImageBO.Filename has a maximum length of 255. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnImageBOFilenameChanging(value);
        }
        partial void OnFilenameChanged();
        partial void OnFilenameChanging(string value);
        partial void OnImageBOFilenameChanged();
        partial void OnImageBOFilenameChanging(string value);
        
        partial void OnExtensionChanged()
        {
            OnImageBOExtensionChanged();
        }
        
        partial void OnExtensionChanging(string value)
        {
            if (value != null && value.Length > 10)
            {
                throw new Exception(String.Format("ImageBO.Extension has a maximum length of 10. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnImageBOExtensionChanging(value);
        }
        partial void OnExtensionChanged();
        partial void OnExtensionChanging(string value);
        partial void OnImageBOExtensionChanged();
        partial void OnImageBOExtensionChanging(string value);
        
        partial void OnIsHeroChanged()
        {
            OnImageBOIsHeroChanged();
        }
        
        partial void OnIsHeroChanging(bool value)
        {
            OnImageBOIsHeroChanging(value);
        }
        partial void OnIsHeroChanged();
        partial void OnIsHeroChanging(bool value);
        partial void OnImageBOIsHeroChanged();
        partial void OnImageBOIsHeroChanging(bool value);
        
        #endregion
        
        #region IComparable Members

        public int CompareTo(object obj)
        {
            if (!(obj is Indico.BusinessObjects.ImageBO))
                return 1;
            Indico.BusinessObjects.ImageBOComparer c = new Indico.BusinessObjects.ImageBOComparer();
            return c.Compare(this, obj as Indico.BusinessObjects.ImageBO);
        }

        #endregion
        #endregion
        
        #region Events
        
        void obj_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == "ID")
            {
                // reload me
                this.SetBO((Indico.DAL.Image)sender);
            }
        }
        
        void Context_OnSendBeforeChanges(object sender, EventArgs e)
        {        
        }
        
        void Context_OnSendAfterChanges(object sender, EventArgs e)
        {   
            if (this.ID > 0)
            {
                this.Cache();
            }
        }

        #endregion
    }
    
    #region ImageBOComparer
    public class ImageBOComparer : IComparer<Indico.BusinessObjects.ImageBO>
    {
        private string propertyToCompareName;
        public ImageBOComparer(string propertyToCompare)
        {
            PropertyInfo p = typeof(Indico.BusinessObjects.ImageBO).GetProperty(propertyToCompare);
            if (p == null)
                throw new ArgumentException("is not a public property of Indico.BusinessObjects.ImageBO", "propertyToCompare");
            this.propertyToCompareName = propertyToCompare;
        }
        
        public ImageBOComparer()
        {
        
        }

        #region IComparer<Indico.BusinessObjects.ImageBO> Members
        public int Compare(Indico.BusinessObjects.ImageBO x, Indico.BusinessObjects.ImageBO y)
        {
            if (propertyToCompareName != null)
            {
                PropertyInfo p = typeof(Indico.BusinessObjects.ImageBO).GetProperty(propertyToCompareName);
                return compare(p, x, y);
            }
            else
            {
                PropertyInfo[] arrP = typeof(Indico.BusinessObjects.ImageBO).GetProperties();
                foreach (PropertyInfo p in arrP)
                {
                    int v = compare(p, x, y);
                    if (v != 0)
                        return v;
                }
                return 0;
            }
        }

        private int compare(PropertyInfo p, Indico.BusinessObjects.ImageBO x, Indico.BusinessObjects.ImageBO y)
        {
            object xVal = p.GetValue(x, null);
            object yVal = p.GetValue(y, null);

            if (xVal == null)
            {
                if (yVal == null)
                    return 0;
                else
                    return -1; // x is null, y is not, y is greater
            }
            else
            {
                if (y == null)
                    return 1; // x non null, y is null, x is greater
                else if (xVal is string)
                {
                    return StringComparer.OrdinalIgnoreCase.Compare(xVal, yVal);
                }
                else if (xVal is IComparable)
                {
                    return ((IComparable)xVal).CompareTo((IComparable)yVal);
                }
                else
                    throw new ArgumentException
                        ("is not string or valuetype that implements IComparable", "propertyToCompare");

            }
        }

        #endregion
    }
    #endregion
}
