// This file is generated by CodeSmith. Do not edit. All edits to this file will be lost. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Xml.Serialization;

using Indico.DAL;

//namespace Indico.BusinessObjects
namespace Indico.BusinessObjects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class PrinterTypeBO : BusinessObject, IComparable
    {
        #region fields
        #region Scalar Fields
        private int id;
        private string _name = string.Empty;
        private string _prefix;
        #endregion
        
        #region Foreign Key fields
        #endregion
        
        #region Foreign Table Foreign Key fields
        [NonSerialized][XmlIgnoreAttribute]
        private IndicoList<Indico.BusinessObjects.PatternBO> patternsWhereThisIsPrinterTypeList;
        [NonSerialized][XmlIgnoreAttribute]
        private bool _patternsWhereThisIsPrinterTypeLoaded;
        #endregion
        
        #region Other fields
        
        private Indico.DAL.PrinterType _objDAL = null;
        private bool _doNotUpdateDALObject = false;
        
        #endregion
        
        #endregion
        
        #region Properties
        /// <summary>The Primary Key for this object</summary>
        public int ID
        {   get {return id;}
            set 
            {
                OnIDChanging(value);
                id = value;
                OnIDChanged();
            }
        }
        
        /// <summary>The name of the Printer Type. The maximum length of this property is 64.</summary>
        public string Name
        {   
            get {return _name;}
            set 
            {
                OnNameChanging(value);
                _name = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Name = value;
                }
                OnNameChanged();
            }
        }
        /// <summary>. The maximum length of this property is 5.</summary>
        public string Prefix
        {   
            get {return _prefix;}
            set 
            {
                OnPrefixChanging(value);
                _prefix = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Prefix = value;
                }
                OnPrefixChanged();
            }
        }
        
        internal Indico.DAL.PrinterType ObjDAL
        {
            get 
            {
                if (_objDAL == null && base._createDAL)
                {
                    _objDAL = this.SetDAL(this.Context.Context);
                    this.ObjDAL.PropertyChanged += new System.ComponentModel.PropertyChangedEventHandler(obj_PropertyChanged);
                }

                return _objDAL;
            }
            set 
            {
                _objDAL = value;
            }
        }
        
        #endregion
        
        #region Non-scalar Properties
        
        #region Foreign Key Objects
        #endregion
        
        #region Foreign Object Foreign Key Collections
        [XmlIgnoreAttribute]
        public IndicoList<Indico.BusinessObjects.PatternBO> PatternsWhereThisIsPrinterType // FK_Pattern_PrinterType
        {
            get
            {
                if (!_patternsWhereThisIsPrinterTypeLoaded)
                {
                    _patternsWhereThisIsPrinterTypeLoaded = true;
                    if (this.ID > 0)
                    {
                         IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
                        Indico.DAL.PrinterType obj = (from o in context.PrinterType
                                     where o.ID == this.ID
                                     select o).FirstOrDefault();

                        obj.PatternsWhereThisIsPrinterType.Load();
                        patternsWhereThisIsPrinterTypeList = new IndicoList<Indico.BusinessObjects.PatternBO>(obj.PatternsWhereThisIsPrinterType.Count);
                        
                        foreach (Indico.DAL.Pattern o in obj.PatternsWhereThisIsPrinterType)
                        {
                            Indico.BusinessObjects.PatternBO fkObj = new Indico.BusinessObjects.PatternBO(o, ref this._context);
                            patternsWhereThisIsPrinterTypeList.Add(fkObj);
                        }
                        
                        if (this.Context == null)
                        {
                            context.Dispose();
                        }
                    }
                    else
                    {
                        patternsWhereThisIsPrinterTypeList = new IndicoList<Indico.BusinessObjects.PatternBO>();
                    }
                    
                    patternsWhereThisIsPrinterTypeList.OnBeforeRemove += new EventHandler(PatternsWhereThisIsPrinterTypeList_OnBeforeRemove);
                    patternsWhereThisIsPrinterTypeList.OnAfterAdd += new EventHandler(PatternsWhereThisIsPrinterTypeList_OnAfterAdd);
                }
                
                return patternsWhereThisIsPrinterTypeList;
            }
        }
        #endregion
        
        #endregion
        
        #region Internal Constructors
        /// <summary>
        /// Creates an instance of the PrinterTypeBO class using the supplied Indico.DAL.PrinterType. 
        /// </summary>
        /// <param name="obj">a Indico.DAL.PrinterType whose properties will be used to initialise the PrinterTypeBO</param>
        internal PrinterTypeBO(Indico.DAL.PrinterType obj, ref IndicoContext context)
        {
            this._doNotUpdateDALObject = true;
            
            this.Context = context;
        
            // set the properties from the Indico.DAL.PrinterType 
            this.ID = obj.ID;
            
            this.Name = obj.Name;
            this.Prefix = obj.Prefix;
            
            this._doNotUpdateDALObject = false;
        }
        #endregion
        
        #region Internal utility methods
        internal Indico.DAL.PrinterType SetDAL(IndicoEntities context)
        {
            this._doNotUpdateDALObject = true;
        
            // set the Indico.DAL.PrinterType properties
            Indico.DAL.PrinterType obj = new Indico.DAL.PrinterType();
            
            if (this.ID > 0)
            {
                obj = context.PrinterType.FirstOrDefault<PrinterType>(o => o.ID == this.ID);
            }
            
            obj.Name = this.Name;
            obj.Prefix = this.Prefix;
            
            
            if (_patternsWhereThisIsPrinterTypeLoaded)
                BusinessObject.SynchroniseEntityList(
                    Indico.BusinessObjects.PatternBO.ToEntityList(this.PatternsWhereThisIsPrinterType, context), 
                    obj.PatternsWhereThisIsPrinterType);
            
            this._doNotUpdateDALObject = false;
            
            return obj;
        }
        
        internal void SetBO(System.Data.Objects.DataClasses.EntityObject eObj)
        {
            this._doNotUpdateDALObject = true;
            
            // Check the received type
            if (eObj.GetType() != typeof(Indico.DAL.PrinterType))
            {
                throw new FormatException("Received wrong parameter type...");
            }

            Indico.DAL.PrinterType obj = (Indico.DAL.PrinterType)eObj;
            
            // set the Indico.BusinessObjects.PrinterTypeBO properties
            this.ID = obj.ID;
            
            this.Name = obj.Name;
            this.Prefix = obj.Prefix;
            
            
            this._doNotUpdateDALObject = false;
        }
        
        internal void SetBO(Indico.BusinessObjects.PrinterTypeBO obj)
        {
            this._doNotUpdateDALObject = true;
            
            // set this Indico.BusinessObjects.PrinterTypeBO properties
            this.ID = obj.ID;
            
            this.Name = obj.Name;
            this.Prefix = obj.Prefix;
            
            this._doNotUpdateDALObject = false;
        }
        
        internal List<Indico.BusinessObjects.PrinterTypeBO> IQueryableToList(IQueryable<Indico.DAL.PrinterType> oQuery)
        {
            List<Indico.DAL.PrinterType> oList = oQuery.ToList();
            List<Indico.BusinessObjects.PrinterTypeBO> rList = new List<Indico.BusinessObjects.PrinterTypeBO>(oList.Count);
            foreach (Indico.DAL.PrinterType o in oList)
            {
                Indico.BusinessObjects.PrinterTypeBO obj = new Indico.BusinessObjects.PrinterTypeBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal List<Indico.BusinessObjects.PrinterTypeBO> ToList(IEnumerable<Indico.DAL.PrinterType> oQuery)
        {
            List<Indico.DAL.PrinterType> oList = oQuery.ToList();
            List<Indico.BusinessObjects.PrinterTypeBO> rList = new List<Indico.BusinessObjects.PrinterTypeBO>(oList.Count);
            foreach (Indico.DAL.PrinterType o in oList)
            {
                Indico.BusinessObjects.PrinterTypeBO obj = new Indico.BusinessObjects.PrinterTypeBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal static List<Indico.DAL.PrinterType> ToEntityList(List<PrinterTypeBO> bos, IndicoEntities context)
        {
            // build a List of PrinterType entities from the business objects
            List<Int32> ids = (from o in bos
                                   select o.ID).ToList<Int32>();

            return (context.PrinterType.Count() == 0) ? new List<Indico.DAL.PrinterType>() : (context.PrinterType.Where(BuildContainsExpression<PrinterType, int>(e => e.ID, ids)))
                .ToList<Indico.DAL.PrinterType>();
        }
        
        internal static System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.PrinterType> ToEntityCollection(List<PrinterTypeBO> bos, IndicoEntities context)
        {
            // build an EntityCollection of PrinterType entities from the business objects
            List<Int32> ids = (from o in bos
                               select o.ID).ToList<Int32>();

            List<Indico.DAL.PrinterType> el = (context.PrinterType.Count() == 0) ? new List<Indico.DAL.PrinterType>() : 
                context.PrinterType.Where(BuildContainsExpression<PrinterType, int>(e => e.ID, ids))
                .ToList<Indico.DAL.PrinterType>();
                
            System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.PrinterType> ec 
                = new System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.PrinterType>();
                
            foreach (Indico.DAL.PrinterType r in el) 
            {
                ec.Add(r);
            }
            return ec;
        }

        internal Indico.DAL.PrinterType ToEntity(IndicoEntities context)
        {
            return (from o in context.PrinterType
                    where o.ID == this.ID
                    select o).FirstOrDefault();
        }
        #endregion
        
        #region BusinessObject methods
        
        #region Add Object
        
        public void Add()
        {
            if (this.Context != null)
            {
                this.Context.Context.AddToPrinterType(this.ObjDAL);
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.PrinterType obj = this.SetDAL(objContext.Context);
                objContext.Context.AddToPrinterType(obj);
                objContext.SaveChanges();
                objContext.Dispose(); 
            }
        }
        
        #endregion
        
        #region Delete Object
        
        public void Delete()
        {
            if (this.Context != null)
            {
                if (this.ObjDAL != null && this.ObjDAL.EntityKey != null)
                {
                    if (this.ObjDAL.EntityState == System.Data.EntityState.Detached)
                    {
                        this.Context.Context.Attach(this.ObjDAL);
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                    else
                    {
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                }
                else
                {
                    Indico.DAL.PrinterType obj = this.SetDAL(this.Context.Context);
                    this.Context.Context.DeleteObject(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.PrinterType obj = this.SetDAL(objContext.Context);
                this.Context.Context.DeleteObject(obj);
                objContext.Context.SaveChanges();
                objContext.Dispose();
            }
        }
        
        #endregion
        
        #region Get Single Object
        
        public bool GetObject()
        {
            return GetObject(true);
        }
        public bool GetObject(bool blnCache)
        {
            Indico.BusinessObjects.PrinterTypeBO data = null;
            
            if (blnCache)
            {
                data = this.GetFromCache(this.ID) as Indico.BusinessObjects.PrinterTypeBO; 
            }

            if (data != null)
            {
                SetBO(data);
            }
            else
            {
                try
                {
                    IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
                    IQueryable<Indico.DAL.PrinterType> oQuery =
                        from o in context.PrinterType
                        where o.ID == this.ID
                        select o;

                    List<Indico.DAL.PrinterType> oList = oQuery.ToList();
                    if (oList.Count != 1)
                        return false;
                    else
                    {
                        SetBO(oList[0]);
                        this.Cache();
                    }
                    
                    if (this.Context == null)
                    {
                        context.Dispose();
                    }
                }
                catch (System.Exception e)
                {
                    throw new IndicoException(String.Format(System.Globalization.CultureInfo.InvariantCulture, ResourceManager.GetString("Could not Retrieve a {0} from the data store", System.Globalization.CultureInfo.CurrentCulture), this.ToString()), e, IndicoException.Severities.USER, IndicoException.ERRNO.INT_ERR_BO_SELECT_FAIL);
                }
            }
            return true;
        }
        #endregion
        
        #region GetAllObject
        public List<Indico.BusinessObjects.PrinterTypeBO> GetAllObject()
        {
            return GetAllObject(0, 0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> GetAllObject(int maximumRows)
        {
            return GetAllObject(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> GetAllObject(int maximumRows, int startIndex)
        {
            return GetAllObject(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> GetAllObject(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.PrinterType> oQuery =
                (from o in context.PrinterType
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.PrinterTypeBO> printertypes = IQueryableToList(oQuery);
            context.Dispose();
            return printertypes;
        }
        #endregion
        
        #region SearchObjects
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchObjects()
        {
            return SearchObjects(0,0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchObjects(int maximumRows)
        {
            return SearchObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchObjects(int maximumRows, int startIndex)
        {
            return SearchObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.PrinterType> oQuery =
                (from o in context.PrinterType
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.Name == string.Empty || this.Name == o.Name) &&
                    (this.Prefix == null || this.Prefix == o.Prefix) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.PrinterTypeBO> printertypes = IQueryableToList(oQuery);
            
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return printertypes;
        }
        
        public int SearchObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.PrinterType
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.Name == string.Empty || this.Name == o.Name) &&
                    (this.Prefix == null || this.Prefix == o.Prefix) 
                 orderby o.ID
                 select o).Count();
        }
        #endregion
        
        #region SearchObjectsLikeAnd
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeAndObjects()
        {
            return SearchLikeAndObjects(0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeAndObjects(int maximumRows)
        {
            return SearchLikeAndObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeAndObjects(int maximumRows, int startIndex)
        {
            return SearchLikeAndObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeAndObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.PrinterType> oQuery =
                (from o in context.PrinterType
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.Name == string.Empty || o.Name.Contains(this.Name)) &&
                    (this.Prefix == null || o.Prefix.Contains(this.Prefix)) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.PrinterTypeBO> printertypes = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return printertypes;
        }
        
        public int SearchLikeAndObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.PrinterType
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.Name == string.Empty || o.Name.Contains(this.Name)) &&
                    (this.Prefix == null || o.Prefix.Contains(this.Prefix)) 
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region SearchObjectsLikeOr
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeOrObjects()
        {
            return SearchLikeOrObjects(0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeOrObjects(int maximumRows)
        {
            return SearchLikeOrObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeOrObjects(int maximumRows, int startIndex)
        {
            return SearchLikeOrObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.PrinterTypeBO> SearchLikeOrObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.PrinterType> oQuery =
                (from o in context.PrinterType
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    ((o.Name.Contains(this.Name)) ||
                    (o.Prefix.Contains(this.Prefix)) ||
                    (this.Name == null && this.Prefix == null ))
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.PrinterTypeBO> printertypes = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return printertypes;
        }
        
        public int SearchLikeOrObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.PrinterType
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    ((o.Name.Contains(this.Name)) ||
                    (o.Prefix.Contains(this.Prefix)) ||
                    (this.Name == null && this.Prefix == null ))
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region Serialization methods
        /// <summary>
        /// Serializes the Indico.BusinessObjects.PrinterTypeBO to an XML representation
        /// </summary>
        /// <returns>a XML string serialized representation</returns>
        public string SerializeObject()
        {
            string strReturn = "";

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();

            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            x.Serialize(objStream, this);

            System.Text.Encoding encoding = System.Text.Encoding.UTF8;
            // Read string from binary file with UTF8 encoding
            strReturn = encoding.GetString(objStream.GetBuffer());

            objStream.Close();
            return strReturn;

        }

        /// <summary>
        /// Deserializes Indico.BusinessObjects.PrinterTypeBO object from an XML representation
        /// </summary>
        /// <param name="strXML">a XML string serialized representation</param>
        public Indico.BusinessObjects.PrinterTypeBO DeserializeObject(string strXML)
        {
            Indico.BusinessObjects.PrinterTypeBO objTemp = null;
            System.Xml.XmlDocument objXML = new System.Xml.XmlDocument();

            objXML.LoadXml(strXML);
            System.Text.Encoding encoding = System.Text.Encoding.UTF8;

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();
            byte[] b = encoding.GetBytes(objXML.OuterXml);

            objStream.Write(b, 0, (int)b.Length);
            objStream.Position = 0;
            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            objTemp = (Indico.BusinessObjects.PrinterTypeBO)x.Deserialize(objStream);
            objStream.Close();
            return objTemp;
        }

        /// <summary>
        /// Returns a simple XML representation of Indico.BusinessObjects.PrinterTypeBO object in an XmlElement
        /// </summary>
        /// <returns>An XML snippet representing the object</returns>
        public string ToXmlString()
        {
            // MW TODO - implement this better.
            return SerializeObject();
        }
        #endregion
        
        #region OnPropertyChange Methods
        partial void OnIDChanged()
        {
            OnPrinterTypeBOIDChanged();
        }
        
        partial void OnIDChanging(int value)
        {
            if (value < 0)
            {
                throw new Exception(String.Format("PrinterTypeBO.ID must be more than or equal to 0. The supplied value was {0}.", value));
            }
            OnPrinterTypeBOIDChanging(value);
        }
        partial void OnIDChanged();
        partial void OnIDChanging(int value);
        partial void OnPrinterTypeBOIDChanged();
        partial void OnPrinterTypeBOIDChanging(int value);
        
        partial void OnNameChanged()
        {
            OnPrinterTypeBONameChanged();
        }
        
        partial void OnNameChanging(string value)
        {
            if (value != null && value.Length > 64)
            {
                throw new Exception(String.Format("PrinterTypeBO.Name has a maximum length of 64. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnPrinterTypeBONameChanging(value);
        }
        partial void OnNameChanged();
        partial void OnNameChanging(string value);
        partial void OnPrinterTypeBONameChanged();
        partial void OnPrinterTypeBONameChanging(string value);
        
        partial void OnPrefixChanged()
        {
            OnPrinterTypeBOPrefixChanged();
        }
        
        partial void OnPrefixChanging(string value)
        {
            if (value != null && value.Length > 5)
            {
                throw new Exception(String.Format("PrinterTypeBO.Prefix has a maximum length of 5. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnPrinterTypeBOPrefixChanging(value);
        }
        partial void OnPrefixChanged();
        partial void OnPrefixChanging(string value);
        partial void OnPrinterTypeBOPrefixChanged();
        partial void OnPrinterTypeBOPrefixChanging(string value);
        
        #endregion
        
        #region IComparable Members

        public int CompareTo(object obj)
        {
            if (!(obj is Indico.BusinessObjects.PrinterTypeBO))
                return 1;
            Indico.BusinessObjects.PrinterTypeBOComparer c = new Indico.BusinessObjects.PrinterTypeBOComparer();
            return c.Compare(this, obj as Indico.BusinessObjects.PrinterTypeBO);
        }

        #endregion
        #endregion
        
        #region Events
        
        void obj_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == "ID")
            {
                // reload me
                this.SetBO((Indico.DAL.PrinterType)sender);
            }
        }
        
        void PatternsWhereThisIsPrinterTypeList_OnAfterAdd(object sender, EventArgs e)
        {
            Indico.DAL.Pattern obj = null;
            if (this.Context != null)
            {
                if (((IndicoList<Indico.BusinessObjects.PatternBO>)sender).Count > 0)
                {
                    obj = ((IndicoList<Indico.BusinessObjects.PatternBO>)sender)[((IndicoList<Indico.BusinessObjects.PatternBO>)sender).Count - 1].ObjDAL;
                    this.ObjDAL.PatternsWhereThisIsPrinterType.Add(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                obj = ((IndicoList<Indico.BusinessObjects.PatternBO>)sender)[((IndicoList<Indico.BusinessObjects.PatternBO>)sender).Count - 1].SetDAL(objContext.Context);
                this.ObjDAL.PatternsWhereThisIsPrinterType.Add(obj);
                objContext.SaveChanges();
                objContext.Dispose();
            }
        }
        
        void PatternsWhereThisIsPrinterTypeList_OnBeforeRemove(object sender, EventArgs e)
        {
            Indico.DAL.Pattern obj = null;
            if (this.Context != null)
            {
                if (((IndicoList<Indico.BusinessObjects.PatternBO>)sender).Count > 0)
                {
                    obj = ((IndicoList<Indico.BusinessObjects.PatternBO>)sender)[((IndicoList<Indico.BusinessObjects.PatternBO>)sender).Count - 1].ObjDAL;
                    this.ObjDAL.PatternsWhereThisIsPrinterType.Remove(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                obj = ((IndicoList<Indico.BusinessObjects.PatternBO>)sender)[((IndicoList<Indico.BusinessObjects.PatternBO>)sender).Count - 1].SetDAL(objContext.Context);
                this.ObjDAL.PatternsWhereThisIsPrinterType.Remove(obj);
                objContext.SaveChanges();
                objContext.Dispose();
            }
        }
        
        void Context_OnSendBeforeChanges(object sender, EventArgs e)
        {        
            this._patternsWhereThisIsPrinterTypeLoaded = false;
            if (this.patternsWhereThisIsPrinterTypeList != null)
            {
                this.patternsWhereThisIsPrinterTypeList.OnBeforeRemove -= new EventHandler(PatternsWhereThisIsPrinterTypeList_OnBeforeRemove);
                this.patternsWhereThisIsPrinterTypeList.OnAfterAdd -= new EventHandler(PatternsWhereThisIsPrinterTypeList_OnAfterAdd);
            }
        }
        
        void Context_OnSendAfterChanges(object sender, EventArgs e)
        {   
            if (this.ID > 0)
            {
                this.Cache();
            }
        }

        #endregion
    }
    
    #region PrinterTypeBOComparer
    public class PrinterTypeBOComparer : IComparer<Indico.BusinessObjects.PrinterTypeBO>
    {
        private string propertyToCompareName;
        public PrinterTypeBOComparer(string propertyToCompare)
        {
            PropertyInfo p = typeof(Indico.BusinessObjects.PrinterTypeBO).GetProperty(propertyToCompare);
            if (p == null)
                throw new ArgumentException("is not a public property of Indico.BusinessObjects.PrinterTypeBO", "propertyToCompare");
            this.propertyToCompareName = propertyToCompare;
        }
        
        public PrinterTypeBOComparer()
        {
        
        }

        #region IComparer<Indico.BusinessObjects.PrinterTypeBO> Members
        public int Compare(Indico.BusinessObjects.PrinterTypeBO x, Indico.BusinessObjects.PrinterTypeBO y)
        {
            if (propertyToCompareName != null)
            {
                PropertyInfo p = typeof(Indico.BusinessObjects.PrinterTypeBO).GetProperty(propertyToCompareName);
                return compare(p, x, y);
            }
            else
            {
                PropertyInfo[] arrP = typeof(Indico.BusinessObjects.PrinterTypeBO).GetProperties();
                foreach (PropertyInfo p in arrP)
                {
                    int v = compare(p, x, y);
                    if (v != 0)
                        return v;
                }
                return 0;
            }
        }

        private int compare(PropertyInfo p, Indico.BusinessObjects.PrinterTypeBO x, Indico.BusinessObjects.PrinterTypeBO y)
        {
            object xVal = p.GetValue(x, null);
            object yVal = p.GetValue(y, null);

            if (xVal == null)
            {
                if (yVal == null)
                    return 0;
                else
                    return -1; // x is null, y is not, y is greater
            }
            else
            {
                if (y == null)
                    return 1; // x non null, y is null, x is greater
                else if (xVal is string)
                {
                    return StringComparer.OrdinalIgnoreCase.Compare(xVal, yVal);
                }
                else if (xVal is IComparable)
                {
                    return ((IComparable)xVal).CompareTo((IComparable)yVal);
                }
                else
                    throw new ArgumentException
                        ("is not string or valuetype that implements IComparable", "propertyToCompare");

            }
        }

        #endregion
    }
    #endregion
}
