// This file is generated by CodeSmith. Do not edit. All edits to this file will be lost. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Xml.Serialization;

using Indico.DAL;

//namespace Indico.BusinessObjects
namespace Indico.BusinessObjects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class RoleBO : BusinessObject, IComparable
    {
        #region fields
        #region Scalar Fields
        private int id;
        private string _description;
        private string _name = string.Empty;
        #endregion
        
        #region Foreign Key fields
        #endregion
        
        #region Foreign Table Foreign Key fields
        [NonSerialized][XmlIgnoreAttribute]
        private IndicoList<Indico.BusinessObjects.MenuItemBO> menuItemRolesWhereThisIsRoleList;
        [NonSerialized][XmlIgnoreAttribute]
        private bool _menuItemRolesWhereThisIsRoleLoaded;
        [NonSerialized][XmlIgnoreAttribute]
        private IndicoList<Indico.BusinessObjects.UserBO> userRolesWhereThisIsRoleList;
        [NonSerialized][XmlIgnoreAttribute]
        private bool _userRolesWhereThisIsRoleLoaded;
        #endregion
        
        #region Other fields
        
        private Indico.DAL.Role _objDAL = null;
        private bool _doNotUpdateDALObject = false;
        
        #endregion
        
        #endregion
        
        #region Properties
        /// <summary>The Primary Key for this object</summary>
        public int ID
        {   get {return id;}
            set 
            {
                OnIDChanging(value);
                id = value;
                OnIDChanged();
            }
        }
        
        /// <summary>The description of the Role. The maximum length of this property is 256.</summary>
        public string Description
        {   
            get {return _description;}
            set 
            {
                OnDescriptionChanging(value);
                _description = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Description = value;
                }
                OnDescriptionChanged();
            }
        }
        /// <summary>The name of the Role. The maximum length of this property is 64.</summary>
        public string Name
        {   
            get {return _name;}
            set 
            {
                OnNameChanging(value);
                _name = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Name = value;
                }
                OnNameChanged();
            }
        }
        
        internal Indico.DAL.Role ObjDAL
        {
            get 
            {
                if (_objDAL == null && base._createDAL)
                {
                    _objDAL = this.SetDAL(this.Context.Context);
                    this.ObjDAL.PropertyChanged += new System.ComponentModel.PropertyChangedEventHandler(obj_PropertyChanged);
                }

                return _objDAL;
            }
            set 
            {
                _objDAL = value;
            }
        }
        
        #endregion
        
        #region Non-scalar Properties
        
        #region Foreign Key Objects
        #endregion
        
        #region Foreign Object Foreign Key Collections
        [XmlIgnoreAttribute]
        public IndicoList<Indico.BusinessObjects.MenuItemBO> MenuItemRolesWhereThisIsRole // FK_MenuItemRole_Role
        {
            get
            {
                if (!_menuItemRolesWhereThisIsRoleLoaded)
                {
                    _menuItemRolesWhereThisIsRoleLoaded = true;
                    if (this.ID > 0)
                    {
                         IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
                        Indico.DAL.Role obj = (from o in context.Role
                                     where o.ID == this.ID
                                     select o).FirstOrDefault();

                        obj.MenuItemRolesWhereThisIsRole.Load();
                        menuItemRolesWhereThisIsRoleList = new IndicoList<Indico.BusinessObjects.MenuItemBO>(obj.MenuItemRolesWhereThisIsRole.Count);
                        
                        foreach (Indico.DAL.MenuItem o in obj.MenuItemRolesWhereThisIsRole)
                        {
                            Indico.BusinessObjects.MenuItemBO fkObj = new Indico.BusinessObjects.MenuItemBO(o, ref this._context);
                            menuItemRolesWhereThisIsRoleList.Add(fkObj);
                        }
                        
                        if (this.Context == null)
                        {
                            context.Dispose();
                        }
                    }
                    else
                    {
                        menuItemRolesWhereThisIsRoleList = new IndicoList<Indico.BusinessObjects.MenuItemBO>();
                    }
                    
                    menuItemRolesWhereThisIsRoleList.OnBeforeRemove += new EventHandler(MenuItemRolesWhereThisIsRoleList_OnBeforeRemove);
                    menuItemRolesWhereThisIsRoleList.OnAfterAdd += new EventHandler(MenuItemRolesWhereThisIsRoleList_OnAfterAdd);
                }
                
                return menuItemRolesWhereThisIsRoleList;
            }
        }
        [XmlIgnoreAttribute]
        public IndicoList<Indico.BusinessObjects.UserBO> UserRolesWhereThisIsRole // FK_UserRole_Role
        {
            get
            {
                if (!_userRolesWhereThisIsRoleLoaded)
                {
                    _userRolesWhereThisIsRoleLoaded = true;
                    if (this.ID > 0)
                    {
                         IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
                        Indico.DAL.Role obj = (from o in context.Role
                                     where o.ID == this.ID
                                     select o).FirstOrDefault();

                        obj.UserRolesWhereThisIsRole.Load();
                        userRolesWhereThisIsRoleList = new IndicoList<Indico.BusinessObjects.UserBO>(obj.UserRolesWhereThisIsRole.Count);
                        
                        foreach (Indico.DAL.User o in obj.UserRolesWhereThisIsRole)
                        {
                            Indico.BusinessObjects.UserBO fkObj = new Indico.BusinessObjects.UserBO(o, ref this._context);
                            userRolesWhereThisIsRoleList.Add(fkObj);
                        }
                        
                        if (this.Context == null)
                        {
                            context.Dispose();
                        }
                    }
                    else
                    {
                        userRolesWhereThisIsRoleList = new IndicoList<Indico.BusinessObjects.UserBO>();
                    }
                    
                    userRolesWhereThisIsRoleList.OnBeforeRemove += new EventHandler(UserRolesWhereThisIsRoleList_OnBeforeRemove);
                    userRolesWhereThisIsRoleList.OnAfterAdd += new EventHandler(UserRolesWhereThisIsRoleList_OnAfterAdd);
                }
                
                return userRolesWhereThisIsRoleList;
            }
        }
        #endregion
        
        #endregion
        
        #region Internal Constructors
        /// <summary>
        /// Creates an instance of the RoleBO class using the supplied Indico.DAL.Role. 
        /// </summary>
        /// <param name="obj">a Indico.DAL.Role whose properties will be used to initialise the RoleBO</param>
        internal RoleBO(Indico.DAL.Role obj, ref IndicoContext context)
        {
            this._doNotUpdateDALObject = true;
            
            this.Context = context;
        
            // set the properties from the Indico.DAL.Role 
            this.ID = obj.ID;
            
            this.Description = obj.Description;
            this.Name = obj.Name;
            
            this._doNotUpdateDALObject = false;
        }
        #endregion
        
        #region Internal utility methods
        internal Indico.DAL.Role SetDAL(IndicoEntities context)
        {
            this._doNotUpdateDALObject = true;
        
            // set the Indico.DAL.Role properties
            Indico.DAL.Role obj = new Indico.DAL.Role();
            
            if (this.ID > 0)
            {
                obj = context.Role.FirstOrDefault<Role>(o => o.ID == this.ID);
            }
            
            obj.Description = this.Description;
            obj.Name = this.Name;
            
            
            if (_menuItemRolesWhereThisIsRoleLoaded)
                BusinessObject.SynchroniseEntityList(
                    Indico.BusinessObjects.MenuItemBO.ToEntityList(this.MenuItemRolesWhereThisIsRole, context), 
                    obj.MenuItemRolesWhereThisIsRole);
            if (_userRolesWhereThisIsRoleLoaded)
                BusinessObject.SynchroniseEntityList(
                    Indico.BusinessObjects.UserBO.ToEntityList(this.UserRolesWhereThisIsRole, context), 
                    obj.UserRolesWhereThisIsRole);
            
            this._doNotUpdateDALObject = false;
            
            return obj;
        }
        
        internal void SetBO(System.Data.Objects.DataClasses.EntityObject eObj)
        {
            this._doNotUpdateDALObject = true;
            
            // Check the received type
            if (eObj.GetType() != typeof(Indico.DAL.Role))
            {
                throw new FormatException("Received wrong parameter type...");
            }

            Indico.DAL.Role obj = (Indico.DAL.Role)eObj;
            
            // set the Indico.BusinessObjects.RoleBO properties
            this.ID = obj.ID;
            
            this.Description = obj.Description;
            this.Name = obj.Name;
            
            
            this._doNotUpdateDALObject = false;
        }
        
        internal void SetBO(Indico.BusinessObjects.RoleBO obj)
        {
            this._doNotUpdateDALObject = true;
            
            // set this Indico.BusinessObjects.RoleBO properties
            this.ID = obj.ID;
            
            this.Description = obj.Description;
            this.Name = obj.Name;
            
            this._doNotUpdateDALObject = false;
        }
        
        internal List<Indico.BusinessObjects.RoleBO> IQueryableToList(IQueryable<Indico.DAL.Role> oQuery)
        {
            List<Indico.DAL.Role> oList = oQuery.ToList();
            List<Indico.BusinessObjects.RoleBO> rList = new List<Indico.BusinessObjects.RoleBO>(oList.Count);
            foreach (Indico.DAL.Role o in oList)
            {
                Indico.BusinessObjects.RoleBO obj = new Indico.BusinessObjects.RoleBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal List<Indico.BusinessObjects.RoleBO> ToList(IEnumerable<Indico.DAL.Role> oQuery)
        {
            List<Indico.DAL.Role> oList = oQuery.ToList();
            List<Indico.BusinessObjects.RoleBO> rList = new List<Indico.BusinessObjects.RoleBO>(oList.Count);
            foreach (Indico.DAL.Role o in oList)
            {
                Indico.BusinessObjects.RoleBO obj = new Indico.BusinessObjects.RoleBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal static List<Indico.DAL.Role> ToEntityList(List<RoleBO> bos, IndicoEntities context)
        {
            // build a List of Role entities from the business objects
            List<Int32> ids = (from o in bos
                                   select o.ID).ToList<Int32>();

            return (context.Role.Count() == 0) ? new List<Indico.DAL.Role>() : (context.Role.Where(BuildContainsExpression<Role, int>(e => e.ID, ids)))
                .ToList<Indico.DAL.Role>();
        }
        
        internal static System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.Role> ToEntityCollection(List<RoleBO> bos, IndicoEntities context)
        {
            // build an EntityCollection of Role entities from the business objects
            List<Int32> ids = (from o in bos
                               select o.ID).ToList<Int32>();

            List<Indico.DAL.Role> el = (context.Role.Count() == 0) ? new List<Indico.DAL.Role>() : 
                context.Role.Where(BuildContainsExpression<Role, int>(e => e.ID, ids))
                .ToList<Indico.DAL.Role>();
                
            System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.Role> ec 
                = new System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.Role>();
                
            foreach (Indico.DAL.Role r in el) 
            {
                ec.Add(r);
            }
            return ec;
        }

        internal Indico.DAL.Role ToEntity(IndicoEntities context)
        {
            return (from o in context.Role
                    where o.ID == this.ID
                    select o).FirstOrDefault();
        }
        #endregion
        
        #region BusinessObject methods
        
        #region Add Object
        
        public void Add()
        {
            if (this.Context != null)
            {
                this.Context.Context.AddToRole(this.ObjDAL);
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.Role obj = this.SetDAL(objContext.Context);
                objContext.Context.AddToRole(obj);
                objContext.SaveChanges();
                objContext.Dispose(); 
            }
        }
        
        #endregion
        
        #region Delete Object
        
        public void Delete()
        {
            if (this.Context != null)
            {
                if (this.ObjDAL != null && this.ObjDAL.EntityKey != null)
                {
                    if (this.ObjDAL.EntityState == System.Data.EntityState.Detached)
                    {
                        this.Context.Context.Attach(this.ObjDAL);
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                    else
                    {
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                }
                else
                {
                    Indico.DAL.Role obj = this.SetDAL(this.Context.Context);
                    this.Context.Context.DeleteObject(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.Role obj = this.SetDAL(objContext.Context);
                this.Context.Context.DeleteObject(obj);
                objContext.Context.SaveChanges();
                objContext.Dispose();
            }
        }
        
        #endregion
        
        #region Get Single Object
        
        public bool GetObject()
        {
            return GetObject(true);
        }
        public bool GetObject(bool blnCache)
        {
            Indico.BusinessObjects.RoleBO data = null;
            
            if (blnCache)
            {
                data = this.GetFromCache(this.ID) as Indico.BusinessObjects.RoleBO; 
            }

            if (data != null)
            {
                SetBO(data);
            }
            else
            {
                try
                {
                    IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
                    IQueryable<Indico.DAL.Role> oQuery =
                        from o in context.Role
                        where o.ID == this.ID
                        select o;

                    List<Indico.DAL.Role> oList = oQuery.ToList();
                    if (oList.Count != 1)
                        return false;
                    else
                    {
                        SetBO(oList[0]);
                        this.Cache();
                    }
                    
                    if (this.Context == null)
                    {
                        context.Dispose();
                    }
                }
                catch (System.Exception e)
                {
                    throw new IndicoException(String.Format(System.Globalization.CultureInfo.InvariantCulture, ResourceManager.GetString("Could not Retrieve a {0} from the data store", System.Globalization.CultureInfo.CurrentCulture), this.ToString()), e, IndicoException.Severities.USER, IndicoException.ERRNO.INT_ERR_BO_SELECT_FAIL);
                }
            }
            return true;
        }
        #endregion
        
        #region GetAllObject
        public List<Indico.BusinessObjects.RoleBO> GetAllObject()
        {
            return GetAllObject(0, 0);
        }
        public List<Indico.BusinessObjects.RoleBO> GetAllObject(int maximumRows)
        {
            return GetAllObject(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.RoleBO> GetAllObject(int maximumRows, int startIndex)
        {
            return GetAllObject(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.RoleBO> GetAllObject(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.Role> oQuery =
                (from o in context.Role
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.RoleBO> roles = IQueryableToList(oQuery);
            context.Dispose();
            return roles;
        }
        #endregion
        
        #region SearchObjects
        public List<Indico.BusinessObjects.RoleBO> SearchObjects()
        {
            return SearchObjects(0,0);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchObjects(int maximumRows)
        {
            return SearchObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchObjects(int maximumRows, int startIndex)
        {
            return SearchObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.Role> oQuery =
                (from o in context.Role
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.Name == string.Empty || this.Name == o.Name) &&
                    (this.Description == null || this.Description == o.Description) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.RoleBO> roles = IQueryableToList(oQuery);
            
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return roles;
        }
        
        public int SearchObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.Role
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.Name == string.Empty || this.Name == o.Name) &&
                    (this.Description == null || this.Description == o.Description) 
                 orderby o.ID
                 select o).Count();
        }
        #endregion
        
        #region SearchObjectsLikeAnd
        public List<Indico.BusinessObjects.RoleBO> SearchLikeAndObjects()
        {
            return SearchLikeAndObjects(0);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchLikeAndObjects(int maximumRows)
        {
            return SearchLikeAndObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchLikeAndObjects(int maximumRows, int startIndex)
        {
            return SearchLikeAndObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchLikeAndObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.Role> oQuery =
                (from o in context.Role
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.Name == string.Empty || o.Name.Contains(this.Name)) &&
                    (this.Description == null || o.Description.Contains(this.Description)) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.RoleBO> roles = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return roles;
        }
        
        public int SearchLikeAndObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.Role
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.Name == string.Empty || o.Name.Contains(this.Name)) &&
                    (this.Description == null || o.Description.Contains(this.Description)) 
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region SearchObjectsLikeOr
        public List<Indico.BusinessObjects.RoleBO> SearchLikeOrObjects()
        {
            return SearchLikeOrObjects(0);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchLikeOrObjects(int maximumRows)
        {
            return SearchLikeOrObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchLikeOrObjects(int maximumRows, int startIndex)
        {
            return SearchLikeOrObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.RoleBO> SearchLikeOrObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.Role> oQuery =
                (from o in context.Role
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    ((o.Name.Contains(this.Name)) ||
                    (o.Description.Contains(this.Description)) ||
                    (this.Name == null && this.Description == null ))
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.RoleBO> roles = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return roles;
        }
        
        public int SearchLikeOrObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.Role
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    ((o.Name.Contains(this.Name)) ||
                    (o.Description.Contains(this.Description)) ||
                    (this.Name == null && this.Description == null ))
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region Serialization methods
        /// <summary>
        /// Serializes the Indico.BusinessObjects.RoleBO to an XML representation
        /// </summary>
        /// <returns>a XML string serialized representation</returns>
        public string SerializeObject()
        {
            string strReturn = "";

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();

            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            x.Serialize(objStream, this);

            System.Text.Encoding encoding = System.Text.Encoding.UTF8;
            // Read string from binary file with UTF8 encoding
            strReturn = encoding.GetString(objStream.GetBuffer());

            objStream.Close();
            return strReturn;

        }

        /// <summary>
        /// Deserializes Indico.BusinessObjects.RoleBO object from an XML representation
        /// </summary>
        /// <param name="strXML">a XML string serialized representation</param>
        public Indico.BusinessObjects.RoleBO DeserializeObject(string strXML)
        {
            Indico.BusinessObjects.RoleBO objTemp = null;
            System.Xml.XmlDocument objXML = new System.Xml.XmlDocument();

            objXML.LoadXml(strXML);
            System.Text.Encoding encoding = System.Text.Encoding.UTF8;

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();
            byte[] b = encoding.GetBytes(objXML.OuterXml);

            objStream.Write(b, 0, (int)b.Length);
            objStream.Position = 0;
            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            objTemp = (Indico.BusinessObjects.RoleBO)x.Deserialize(objStream);
            objStream.Close();
            return objTemp;
        }

        /// <summary>
        /// Returns a simple XML representation of Indico.BusinessObjects.RoleBO object in an XmlElement
        /// </summary>
        /// <returns>An XML snippet representing the object</returns>
        public string ToXmlString()
        {
            // MW TODO - implement this better.
            return SerializeObject();
        }
        #endregion
        
        #region OnPropertyChange Methods
        partial void OnIDChanged()
        {
            OnRoleBOIDChanged();
        }
        
        partial void OnIDChanging(int value)
        {
            if (value < 0)
            {
                throw new Exception(String.Format("RoleBO.ID must be more than or equal to 0. The supplied value was {0}.", value));
            }
            OnRoleBOIDChanging(value);
        }
        partial void OnIDChanged();
        partial void OnIDChanging(int value);
        partial void OnRoleBOIDChanged();
        partial void OnRoleBOIDChanging(int value);
        
        partial void OnNameChanged()
        {
            OnRoleBONameChanged();
        }
        
        partial void OnNameChanging(string value)
        {
            if (value != null && value.Length > 64)
            {
                throw new Exception(String.Format("RoleBO.Name has a maximum length of 64. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnRoleBONameChanging(value);
        }
        partial void OnNameChanged();
        partial void OnNameChanging(string value);
        partial void OnRoleBONameChanged();
        partial void OnRoleBONameChanging(string value);
        
        partial void OnDescriptionChanged()
        {
            OnRoleBODescriptionChanged();
        }
        
        partial void OnDescriptionChanging(string value)
        {
            if (value != null && value.Length > 256)
            {
                throw new Exception(String.Format("RoleBO.Description has a maximum length of 256. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnRoleBODescriptionChanging(value);
        }
        partial void OnDescriptionChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnRoleBODescriptionChanged();
        partial void OnRoleBODescriptionChanging(string value);
        
        #endregion
        
        #region IComparable Members

        public int CompareTo(object obj)
        {
            if (!(obj is Indico.BusinessObjects.RoleBO))
                return 1;
            Indico.BusinessObjects.RoleBOComparer c = new Indico.BusinessObjects.RoleBOComparer();
            return c.Compare(this, obj as Indico.BusinessObjects.RoleBO);
        }

        #endregion
        #endregion
        
        #region Events
        
        void obj_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == "ID")
            {
                // reload me
                this.SetBO((Indico.DAL.Role)sender);
            }
        }
        
        void MenuItemRolesWhereThisIsRoleList_OnAfterAdd(object sender, EventArgs e)
        {
            Indico.DAL.MenuItem obj = null;
            if (this.Context != null)
            {
                if (((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender).Count > 0)
                {
                    obj = ((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender)[((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender).Count - 1].ObjDAL;
                    this.ObjDAL.MenuItemRolesWhereThisIsRole.Add(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                obj = ((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender)[((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender).Count - 1].SetDAL(objContext.Context);
                this.ObjDAL.MenuItemRolesWhereThisIsRole.Add(obj);
                objContext.SaveChanges();
                objContext.Dispose();
            }
        }
        
        void MenuItemRolesWhereThisIsRoleList_OnBeforeRemove(object sender, EventArgs e)
        {
            Indico.DAL.MenuItem obj = null;
            if (this.Context != null)
            {
                if (((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender).Count > 0)
                {
                    obj = ((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender)[((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender).Count - 1].ObjDAL;
                    this.ObjDAL.MenuItemRolesWhereThisIsRole.Remove(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                obj = ((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender)[((IndicoList<Indico.BusinessObjects.MenuItemBO>)sender).Count - 1].SetDAL(objContext.Context);
                this.ObjDAL.MenuItemRolesWhereThisIsRole.Remove(obj);
                objContext.SaveChanges();
                objContext.Dispose();
            }
        }
        
        void UserRolesWhereThisIsRoleList_OnAfterAdd(object sender, EventArgs e)
        {
            Indico.DAL.User obj = null;
            if (this.Context != null)
            {
                if (((IndicoList<Indico.BusinessObjects.UserBO>)sender).Count > 0)
                {
                    obj = ((IndicoList<Indico.BusinessObjects.UserBO>)sender)[((IndicoList<Indico.BusinessObjects.UserBO>)sender).Count - 1].ObjDAL;
                    this.ObjDAL.UserRolesWhereThisIsRole.Add(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                obj = ((IndicoList<Indico.BusinessObjects.UserBO>)sender)[((IndicoList<Indico.BusinessObjects.UserBO>)sender).Count - 1].SetDAL(objContext.Context);
                this.ObjDAL.UserRolesWhereThisIsRole.Add(obj);
                objContext.SaveChanges();
                objContext.Dispose();
            }
        }
        
        void UserRolesWhereThisIsRoleList_OnBeforeRemove(object sender, EventArgs e)
        {
            Indico.DAL.User obj = null;
            if (this.Context != null)
            {
                if (((IndicoList<Indico.BusinessObjects.UserBO>)sender).Count > 0)
                {
                    obj = ((IndicoList<Indico.BusinessObjects.UserBO>)sender)[((IndicoList<Indico.BusinessObjects.UserBO>)sender).Count - 1].ObjDAL;
                    this.ObjDAL.UserRolesWhereThisIsRole.Remove(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                obj = ((IndicoList<Indico.BusinessObjects.UserBO>)sender)[((IndicoList<Indico.BusinessObjects.UserBO>)sender).Count - 1].SetDAL(objContext.Context);
                this.ObjDAL.UserRolesWhereThisIsRole.Remove(obj);
                objContext.SaveChanges();
                objContext.Dispose();
            }
        }
        
        void Context_OnSendBeforeChanges(object sender, EventArgs e)
        {        
            this._menuItemRolesWhereThisIsRoleLoaded = false;
            if (this.menuItemRolesWhereThisIsRoleList != null)
            {
                this.menuItemRolesWhereThisIsRoleList.OnBeforeRemove -= new EventHandler(MenuItemRolesWhereThisIsRoleList_OnBeforeRemove);
                this.menuItemRolesWhereThisIsRoleList.OnAfterAdd -= new EventHandler(MenuItemRolesWhereThisIsRoleList_OnAfterAdd);
            }
            this._userRolesWhereThisIsRoleLoaded = false;
            if (this.userRolesWhereThisIsRoleList != null)
            {
                this.userRolesWhereThisIsRoleList.OnBeforeRemove -= new EventHandler(UserRolesWhereThisIsRoleList_OnBeforeRemove);
                this.userRolesWhereThisIsRoleList.OnAfterAdd -= new EventHandler(UserRolesWhereThisIsRoleList_OnAfterAdd);
            }
        }
        
        void Context_OnSendAfterChanges(object sender, EventArgs e)
        {   
            if (this.ID > 0)
            {
                this.Cache();
            }
        }

        #endregion
    }
    
    #region RoleBOComparer
    public class RoleBOComparer : IComparer<Indico.BusinessObjects.RoleBO>
    {
        private string propertyToCompareName;
        public RoleBOComparer(string propertyToCompare)
        {
            PropertyInfo p = typeof(Indico.BusinessObjects.RoleBO).GetProperty(propertyToCompare);
            if (p == null)
                throw new ArgumentException("is not a public property of Indico.BusinessObjects.RoleBO", "propertyToCompare");
            this.propertyToCompareName = propertyToCompare;
        }
        
        public RoleBOComparer()
        {
        
        }

        #region IComparer<Indico.BusinessObjects.RoleBO> Members
        public int Compare(Indico.BusinessObjects.RoleBO x, Indico.BusinessObjects.RoleBO y)
        {
            if (propertyToCompareName != null)
            {
                PropertyInfo p = typeof(Indico.BusinessObjects.RoleBO).GetProperty(propertyToCompareName);
                return compare(p, x, y);
            }
            else
            {
                PropertyInfo[] arrP = typeof(Indico.BusinessObjects.RoleBO).GetProperties();
                foreach (PropertyInfo p in arrP)
                {
                    int v = compare(p, x, y);
                    if (v != 0)
                        return v;
                }
                return 0;
            }
        }

        private int compare(PropertyInfo p, Indico.BusinessObjects.RoleBO x, Indico.BusinessObjects.RoleBO y)
        {
            object xVal = p.GetValue(x, null);
            object yVal = p.GetValue(y, null);

            if (xVal == null)
            {
                if (yVal == null)
                    return 0;
                else
                    return -1; // x is null, y is not, y is greater
            }
            else
            {
                if (y == null)
                    return 1; // x non null, y is null, x is greater
                else if (xVal is string)
                {
                    return StringComparer.OrdinalIgnoreCase.Compare(xVal, yVal);
                }
                else if (xVal is IComparable)
                {
                    return ((IComparable)xVal).CompareTo((IComparable)yVal);
                }
                else
                    throw new ArgumentException
                        ("is not string or valuetype that implements IComparable", "propertyToCompare");

            }
        }

        #endregion
    }
    #endregion
}
