// This file is generated by CodeSmith. Do not edit. All edits to this file will be lost. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Xml.Serialization;

using Indico.DAL;

//namespace Indico.BusinessObjects
namespace Indico.BusinessObjects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class UserHistoryBO : BusinessObject, IComparable
    {
        #region fields
        #region Scalar Fields
        private int id;
        private int _company;
        private int _creator;
        private DateTime? _dateCreated;
        private string _emailAddress = string.Empty;
        private string _familyName = string.Empty;
        private string _givenName;
        private string _guid = string.Empty;
        private bool _isActive;
        private bool _isDeleted;
        private string _password;
        private int _user;
        private string _username = string.Empty;
        #endregion
        
        #region Foreign Key fields
        [NonSerialized][XmlIgnoreAttribute]
        private Indico.BusinessObjects.UserBO _objCreator;
        [NonSerialized][XmlIgnoreAttribute]
        private Indico.BusinessObjects.UserBO _objUser;
        #endregion
        
        #region Foreign Table Foreign Key fields
        #endregion
        
        #region Other fields
        
        private Indico.DAL.UserHistory _objDAL = null;
        private bool _doNotUpdateDALObject = false;
        
        #endregion
        
        #endregion
        
        #region Properties
        /// <summary>The Primary Key for this object</summary>
        public int ID
        {   get {return id;}
            set 
            {
                OnIDChanging(value);
                id = value;
                OnIDChanged();
            }
        }
        
        /// <summary>The company that this User belongs to.</summary>
        public int Company
        {   
            get {return _company;}
            set 
            {
                OnCompanyChanging(value);
                _company = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Company = value;
                }
                OnCompanyChanged();
            }
        }
        /// <summary>The ID of the user who created this user.</summary>
        public int Creator
        {   
            get {return _creator;}
            set 
            {
                OnCreatorChanging(value);
                _creator = value;
                if (!this._doNotUpdateDALObject && this._context != null && this.ObjDAL != null && ((int)value != 0))
                {
                    this.ObjDAL.Creator = (from o in this._context.Context.User
                                           where o.ID == (int)value
                                           select o).ToList<Indico.DAL.User>()[0];
                }
                else if (!this._doNotUpdateDALObject && this._context != null && this.ObjDAL != null && (int)value == 0)
                    this.ObjDAL.Creator = null;
                OnCreatorChanged();
            }
        }
        /// <summary>the DateTime this user was created.</summary>
        public DateTime? DateCreated
        {   
            get {return _dateCreated;}
            set 
            {
                OnDateCreatedChanging(value);
                _dateCreated = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.DateCreated = value;
                }
                OnDateCreatedChanged();
            }
        }
        /// <summary>the email address associated with this user - all correspondence is directed to this address. The maximum length of this property is 64.</summary>
        public string EmailAddress
        {   
            get {return _emailAddress;}
            set 
            {
                OnEmailAddressChanging(value);
                _emailAddress = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.EmailAddress = value;
                }
                OnEmailAddressChanged();
            }
        }
        /// <summary>the user's family, or surname. The maximum length of this property is 32.</summary>
        public string FamilyName
        {   
            get {return _familyName;}
            set 
            {
                OnFamilyNameChanging(value);
                _familyName = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.FamilyName = value;
                }
                OnFamilyNameChanged();
            }
        }
        /// <summary>The user's given name. The maximum length of this property is 32.</summary>
        public string GivenName
        {   
            get {return _givenName;}
            set 
            {
                OnGivenNameChanging(value);
                _givenName = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.GivenName = value;
                }
                OnGivenNameChanged();
            }
        }
        /// <summary>The guid associated with this user that can be used instead of authentication under certain circumstances. The maximum length of this property is 36.</summary>
        public string Guid
        {   
            get {return _guid;}
            set 
            {
                OnGuidChanging(value);
                _guid = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Guid = value;
                }
                OnGuidChanged();
            }
        }
        /// <summary>If true, this user is active and is able to authenticate with the system.</summary>
        public bool IsActive
        {   
            get {return _isActive;}
            set 
            {
                OnIsActiveChanging(value);
                _isActive = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.IsActive = value;
                }
                OnIsActiveChanged();
            }
        }
        /// <summary>If true, this user is deleted and is no longer available to the system.</summary>
        public bool IsDeleted
        {   
            get {return _isDeleted;}
            set 
            {
                OnIsDeletedChanging(value);
                _isDeleted = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.IsDeleted = value;
                }
                OnIsDeletedChanged();
            }
        }
        /// <summary>The password used for authentication. The maximum length of this property is 255.</summary>
        public string Password
        {   
            get {return _password;}
            set 
            {
                OnPasswordChanging(value);
                _password = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Password = value;
                }
                OnPasswordChanged();
            }
        }
        /// <summary>The ID of the User to which this History pertains.</summary>
        public int User
        {   
            get {return _user;}
            set 
            {
                OnUserChanging(value);
                _user = value;
                if (!this._doNotUpdateDALObject && this._context != null && this.ObjDAL != null && ((int)value != 0))
                {
                    this.ObjDAL.User = (from o in this._context.Context.User
                                           where o.ID == (int)value
                                           select o).ToList<Indico.DAL.User>()[0];
                }
                else if (!this._doNotUpdateDALObject && this._context != null && this.ObjDAL != null && (int)value == 0)
                    this.ObjDAL.User = null;
                OnUserChanged();
            }
        }
        /// <summary>The username used for authentication. The maximum length of this property is 32.</summary>
        public string Username
        {   
            get {return _username;}
            set 
            {
                OnUsernameChanging(value);
                _username = value;
                if (!this._doNotUpdateDALObject && this.Context != null && this.ObjDAL != null){
                    this.ObjDAL.Username = value;
                }
                OnUsernameChanged();
            }
        }
        
        internal Indico.DAL.UserHistory ObjDAL
        {
            get 
            {
                if (_objDAL == null && base._createDAL)
                {
                    _objDAL = this.SetDAL(this.Context.Context);
                    this.ObjDAL.PropertyChanged += new System.ComponentModel.PropertyChangedEventHandler(obj_PropertyChanged);
                }

                return _objDAL;
            }
            set 
            {
                _objDAL = value;
            }
        }
        
        #endregion
        
        #region Non-scalar Properties
        
        #region Foreign Key Objects
        ///<summary>The UserBO object identified by the value of Creator</summary>
        [XmlIgnoreAttribute]
        public Indico.BusinessObjects.UserBO objCreator
        {
            get
            {
                if ( _creator > 0 && _objCreator == null)
                {
                        if (this._context == null)
                        {
                            _objCreator = new Indico.BusinessObjects.UserBO();
                        }
                        else
                        {
                            _objCreator = new Indico.BusinessObjects.UserBO(ref this._context);
                        }
                        _objCreator.ID = _creator;
                        _objCreator.GetObject(); 
                }
                return _objCreator;
            }
            set
            { 
                _objCreator = value;
                _creator = _objCreator.ID;
            }
        }
        ///<summary>The UserBO object identified by the value of User</summary>
        [XmlIgnoreAttribute]
        public Indico.BusinessObjects.UserBO objUser
        {
            get
            {
                if ( _user > 0 && _objUser == null)
                {
                        if (this._context == null)
                        {
                            _objUser = new Indico.BusinessObjects.UserBO();
                        }
                        else
                        {
                            _objUser = new Indico.BusinessObjects.UserBO(ref this._context);
                        }
                        _objUser.ID = _user;
                        _objUser.GetObject(); 
                }
                return _objUser;
            }
            set
            { 
                _objUser = value;
                _user = _objUser.ID;
            }
        }
        #endregion
        
        #region Foreign Object Foreign Key Collections
        #endregion
        
        #endregion
        
        #region Internal Constructors
        /// <summary>
        /// Creates an instance of the UserHistoryBO class using the supplied Indico.DAL.UserHistory. 
        /// </summary>
        /// <param name="obj">a Indico.DAL.UserHistory whose properties will be used to initialise the UserHistoryBO</param>
        internal UserHistoryBO(Indico.DAL.UserHistory obj, ref IndicoContext context)
        {
            this._doNotUpdateDALObject = true;
            
            this.Context = context;
        
            // set the properties from the Indico.DAL.UserHistory 
            this.ID = obj.ID;
            
            this.Company = obj.Company;
            this.Creator = (obj.CreatorReference.EntityKey != null && obj.CreatorReference.EntityKey.EntityKeyValues.Count() > 0)
                ? (int)((System.Data.EntityKeyMember)obj.CreatorReference.EntityKey.EntityKeyValues.GetValue(0)).Value
                : 0;
            this.DateCreated = obj.DateCreated;
            this.EmailAddress = obj.EmailAddress;
            this.FamilyName = obj.FamilyName;
            this.GivenName = obj.GivenName;
            this.Guid = obj.Guid;
            this.IsActive = obj.IsActive;
            this.IsDeleted = obj.IsDeleted;
            this.Password = obj.Password;
            this.User = (obj.UserReference.EntityKey != null && obj.UserReference.EntityKey.EntityKeyValues.Count() > 0)
                ? (int)((System.Data.EntityKeyMember)obj.UserReference.EntityKey.EntityKeyValues.GetValue(0)).Value
                : 0;
            this.Username = obj.Username;
            
            this._doNotUpdateDALObject = false;
        }
        #endregion
        
        #region Internal utility methods
        internal Indico.DAL.UserHistory SetDAL(IndicoEntities context)
        {
            this._doNotUpdateDALObject = true;
        
            // set the Indico.DAL.UserHistory properties
            Indico.DAL.UserHistory obj = new Indico.DAL.UserHistory();
            
            if (this.ID > 0)
            {
                obj = context.UserHistory.FirstOrDefault<UserHistory>(o => o.ID == this.ID);
            }
            
            obj.Company = this.Company;
            obj.DateCreated = this.DateCreated;
            obj.EmailAddress = this.EmailAddress;
            obj.FamilyName = this.FamilyName;
            obj.GivenName = this.GivenName;
            obj.Guid = this.Guid;
            obj.IsActive = this.IsActive;
            obj.IsDeleted = this.IsDeleted;
            obj.Password = this.Password;
            obj.Username = this.Username;
            
            if (this.Creator > 0) obj.Creator = context.User.FirstOrDefault(o => o.ID == this.Creator);
            if (this.User > 0) obj.User = context.User.FirstOrDefault(o => o.ID == this.User);
            
            
            this._doNotUpdateDALObject = false;
            
            return obj;
        }
        
        internal void SetBO(System.Data.Objects.DataClasses.EntityObject eObj)
        {
            this._doNotUpdateDALObject = true;
            
            // Check the received type
            if (eObj.GetType() != typeof(Indico.DAL.UserHistory))
            {
                throw new FormatException("Received wrong parameter type...");
            }

            Indico.DAL.UserHistory obj = (Indico.DAL.UserHistory)eObj;
            
            // set the Indico.BusinessObjects.UserHistoryBO properties
            this.ID = obj.ID;
            
            this.Company = obj.Company;
            this.DateCreated = obj.DateCreated;
            this.EmailAddress = obj.EmailAddress;
            this.FamilyName = obj.FamilyName;
            this.GivenName = obj.GivenName;
            this.Guid = obj.Guid;
            this.IsActive = obj.IsActive;
            this.IsDeleted = obj.IsDeleted;
            this.Password = obj.Password;
            this.Username = obj.Username;
            
            this.Creator = (obj.CreatorReference.EntityKey != null && obj.CreatorReference.EntityKey.EntityKeyValues.Count() > 0)
                ? (int)((System.Data.EntityKeyMember)obj.CreatorReference.EntityKey.EntityKeyValues.GetValue(0)).Value
                : 0;
            this.User = (obj.UserReference.EntityKey != null && obj.UserReference.EntityKey.EntityKeyValues.Count() > 0)
                ? (int)((System.Data.EntityKeyMember)obj.UserReference.EntityKey.EntityKeyValues.GetValue(0)).Value
                : 0;
            
            this._doNotUpdateDALObject = false;
        }
        
        internal void SetBO(Indico.BusinessObjects.UserHistoryBO obj)
        {
            this._doNotUpdateDALObject = true;
            
            // set this Indico.BusinessObjects.UserHistoryBO properties
            this.ID = obj.ID;
            
            this.Company = obj.Company;
            this.Creator = obj.Creator;
            this.DateCreated = obj.DateCreated;
            this.EmailAddress = obj.EmailAddress;
            this.FamilyName = obj.FamilyName;
            this.GivenName = obj.GivenName;
            this.Guid = obj.Guid;
            this.IsActive = obj.IsActive;
            this.IsDeleted = obj.IsDeleted;
            this.Password = obj.Password;
            this.User = obj.User;
            this.Username = obj.Username;
            
            this._doNotUpdateDALObject = false;
        }
        
        internal List<Indico.BusinessObjects.UserHistoryBO> IQueryableToList(IQueryable<Indico.DAL.UserHistory> oQuery)
        {
            List<Indico.DAL.UserHistory> oList = oQuery.ToList();
            List<Indico.BusinessObjects.UserHistoryBO> rList = new List<Indico.BusinessObjects.UserHistoryBO>(oList.Count);
            foreach (Indico.DAL.UserHistory o in oList)
            {
                Indico.BusinessObjects.UserHistoryBO obj = new Indico.BusinessObjects.UserHistoryBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal List<Indico.BusinessObjects.UserHistoryBO> ToList(IEnumerable<Indico.DAL.UserHistory> oQuery)
        {
            List<Indico.DAL.UserHistory> oList = oQuery.ToList();
            List<Indico.BusinessObjects.UserHistoryBO> rList = new List<Indico.BusinessObjects.UserHistoryBO>(oList.Count);
            foreach (Indico.DAL.UserHistory o in oList)
            {
                Indico.BusinessObjects.UserHistoryBO obj = new Indico.BusinessObjects.UserHistoryBO(o, ref this._context);
                rList.Add(obj);
            }
            return rList;
        }
        
        internal static List<Indico.DAL.UserHistory> ToEntityList(List<UserHistoryBO> bos, IndicoEntities context)
        {
            // build a List of UserHistory entities from the business objects
            List<Int32> ids = (from o in bos
                                   select o.ID).ToList<Int32>();

            return (context.UserHistory.Count() == 0) ? new List<Indico.DAL.UserHistory>() : (context.UserHistory.Where(BuildContainsExpression<UserHistory, int>(e => e.ID, ids)))
                .ToList<Indico.DAL.UserHistory>();
        }
        
        internal static System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.UserHistory> ToEntityCollection(List<UserHistoryBO> bos, IndicoEntities context)
        {
            // build an EntityCollection of UserHistory entities from the business objects
            List<Int32> ids = (from o in bos
                               select o.ID).ToList<Int32>();

            List<Indico.DAL.UserHistory> el = (context.UserHistory.Count() == 0) ? new List<Indico.DAL.UserHistory>() : 
                context.UserHistory.Where(BuildContainsExpression<UserHistory, int>(e => e.ID, ids))
                .ToList<Indico.DAL.UserHistory>();
                
            System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.UserHistory> ec 
                = new System.Data.Objects.DataClasses.EntityCollection<Indico.DAL.UserHistory>();
                
            foreach (Indico.DAL.UserHistory r in el) 
            {
                ec.Add(r);
            }
            return ec;
        }

        internal Indico.DAL.UserHistory ToEntity(IndicoEntities context)
        {
            return (from o in context.UserHistory
                    where o.ID == this.ID
                    select o).FirstOrDefault();
        }
        #endregion
        
        #region BusinessObject methods
        
        #region Add Object
        
        public void Add()
        {
            if (this.Context != null)
            {
                this.Context.Context.AddToUserHistory(this.ObjDAL);
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.UserHistory obj = this.SetDAL(objContext.Context);
                objContext.Context.AddToUserHistory(obj);
                objContext.SaveChanges();
                objContext.Dispose(); 
            }
        }
        
        #endregion
        
        #region Delete Object
        
        public void Delete()
        {
            if (this.Context != null)
            {
                if (this.ObjDAL != null && this.ObjDAL.EntityKey != null)
                {
                    if (this.ObjDAL.EntityState == System.Data.EntityState.Detached)
                    {
                        this.Context.Context.Attach(this.ObjDAL);
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                    else
                    {
                        this.Context.Context.DeleteObject(this.ObjDAL);
                    }
                }
                else
                {
                    Indico.DAL.UserHistory obj = this.SetDAL(this.Context.Context);
                    this.Context.Context.DeleteObject(obj);
                }
            }
            else
            {
                IndicoContext objContext = new IndicoContext();
                Indico.DAL.UserHistory obj = this.SetDAL(objContext.Context);
                this.Context.Context.DeleteObject(obj);
                objContext.Context.SaveChanges();
                objContext.Dispose();
            }
        }
        
        #endregion
        
        #region Get Single Object
        
        public bool GetObject()
        {
            return GetObject(true);
        }
        public bool GetObject(bool blnCache)
        {
            Indico.BusinessObjects.UserHistoryBO data = null;
            
            if (blnCache)
            {
                data = this.GetFromCache(this.ID) as Indico.BusinessObjects.UserHistoryBO; 
            }

            if (data != null)
            {
                SetBO(data);
            }
            else
            {
                try
                {
                    IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
                    IQueryable<Indico.DAL.UserHistory> oQuery =
                        from o in context.UserHistory
                        where o.ID == this.ID
                        select o;

                    List<Indico.DAL.UserHistory> oList = oQuery.ToList();
                    if (oList.Count != 1)
                        return false;
                    else
                    {
                        SetBO(oList[0]);
                        this.Cache();
                    }
                    
                    if (this.Context == null)
                    {
                        context.Dispose();
                    }
                }
                catch (System.Exception e)
                {
                    throw new IndicoException(String.Format(System.Globalization.CultureInfo.InvariantCulture, ResourceManager.GetString("Could not Retrieve a {0} from the data store", System.Globalization.CultureInfo.CurrentCulture), this.ToString()), e, IndicoException.Severities.USER, IndicoException.ERRNO.INT_ERR_BO_SELECT_FAIL);
                }
            }
            return true;
        }
        #endregion
        
        #region GetAllObject
        public List<Indico.BusinessObjects.UserHistoryBO> GetAllObject()
        {
            return GetAllObject(0, 0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> GetAllObject(int maximumRows)
        {
            return GetAllObject(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> GetAllObject(int maximumRows, int startIndex)
        {
            return GetAllObject(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> GetAllObject(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = new IndicoEntities();
            IQueryable<Indico.DAL.UserHistory> oQuery =
                (from o in context.UserHistory
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.UserHistoryBO> userhistorys = IQueryableToList(oQuery);
            context.Dispose();
            return userhistorys;
        }
        #endregion
        
        #region SearchObjects
        public List<Indico.BusinessObjects.UserHistoryBO> SearchObjects()
        {
            return SearchObjects(0,0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchObjects(int maximumRows)
        {
            return SearchObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchObjects(int maximumRows, int startIndex)
        {
            return SearchObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.UserHistory> oQuery =
                (from o in context.UserHistory
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.User == 0 || this.User == o.User.ID) &&
                    (this.Company == 0 || this.Company == o.Company) &&
                    (this.Username == string.Empty || this.Username == o.Username) &&
                    (this.Password == null || this.Password == o.Password) &&
                    (this.GivenName == null || this.GivenName == o.GivenName) &&
                    (this.FamilyName == string.Empty || this.FamilyName == o.FamilyName) &&
                    (this.EmailAddress == string.Empty || this.EmailAddress == o.EmailAddress) &&
                    (this.DateCreated == null || this.DateCreated == o.DateCreated) &&
                    (this.Creator == 0 || this.Creator == o.Creator.ID) &&
                    (this.IsActive == false || this.IsActive == o.IsActive) &&
                    (this.IsDeleted == false || this.IsDeleted == o.IsDeleted) &&
                    (this.Guid == string.Empty || this.Guid == o.Guid) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.UserHistoryBO> userhistorys = IQueryableToList(oQuery);
            
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return userhistorys;
        }
        
        public int SearchObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.UserHistory
                 where
                    (this.ID == 0 || this.ID == o.ID) &&
                    (this.User == 0 || this.User == o.User.ID) &&
                    (this.Company == 0 || this.Company == o.Company) &&
                    (this.Username == string.Empty || this.Username == o.Username) &&
                    (this.Password == null || this.Password == o.Password) &&
                    (this.GivenName == null || this.GivenName == o.GivenName) &&
                    (this.FamilyName == string.Empty || this.FamilyName == o.FamilyName) &&
                    (this.EmailAddress == string.Empty || this.EmailAddress == o.EmailAddress) &&
                    (this.DateCreated == null || this.DateCreated == o.DateCreated) &&
                    (this.Creator == 0 || this.Creator == o.Creator.ID) &&
                    (this.IsActive == false || this.IsActive == o.IsActive) &&
                    (this.IsDeleted == false || this.IsDeleted == o.IsDeleted) &&
                    (this.Guid == string.Empty || this.Guid == o.Guid) 
                 orderby o.ID
                 select o).Count();
        }
        #endregion
        
        #region SearchObjectsLikeAnd
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeAndObjects()
        {
            return SearchLikeAndObjects(0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeAndObjects(int maximumRows)
        {
            return SearchLikeAndObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeAndObjects(int maximumRows, int startIndex)
        {
            return SearchLikeAndObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeAndObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.UserHistory> oQuery =
                (from o in context.UserHistory
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.User == 0 || o.User.ID == this.User) &&
                    (this.Company == 0 || o.Company == this.Company) &&
                    (this.Username == string.Empty || o.Username.Contains(this.Username)) &&
                    (this.Password == null || o.Password.Contains(this.Password)) &&
                    (this.GivenName == null || o.GivenName.Contains(this.GivenName)) &&
                    (this.FamilyName == string.Empty || o.FamilyName.Contains(this.FamilyName)) &&
                    (this.EmailAddress == string.Empty || o.EmailAddress.Contains(this.EmailAddress)) &&
                    (this.DateCreated == null || o.DateCreated == this.DateCreated) &&
                    (this.Creator == 0 || o.Creator.ID == this.Creator) &&
                    (this.IsActive == false || o.IsActive == this.IsActive) &&
                    (this.IsDeleted == false || o.IsDeleted == this.IsDeleted) &&
                    (this.Guid == string.Empty || o.Guid.Contains(this.Guid)) 
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.UserHistoryBO> userhistorys = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return userhistorys;
        }
        
        public int SearchLikeAndObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.UserHistory
                 where
                    (this.ID == 0 || o.ID == this.ID) &&
                    (this.User == 0 || o.User.ID == this.User) &&
                    (this.Company == 0 || o.Company == this.Company) &&
                    (this.Username == string.Empty || o.Username.Contains(this.Username)) &&
                    (this.Password == null || o.Password.Contains(this.Password)) &&
                    (this.GivenName == null || o.GivenName.Contains(this.GivenName)) &&
                    (this.FamilyName == string.Empty || o.FamilyName.Contains(this.FamilyName)) &&
                    (this.EmailAddress == string.Empty || o.EmailAddress.Contains(this.EmailAddress)) &&
                    (this.DateCreated == null || o.DateCreated == this.DateCreated) &&
                    (this.Creator == 0 || o.Creator.ID == this.Creator) &&
                    (this.IsActive == false || o.IsActive == this.IsActive) &&
                    (this.IsDeleted == false || o.IsDeleted == this.IsDeleted) &&
                    (this.Guid == string.Empty || o.Guid.Contains(this.Guid)) 
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region SearchObjectsLikeOr
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeOrObjects()
        {
            return SearchLikeOrObjects(0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeOrObjects(int maximumRows)
        {
            return SearchLikeOrObjects(maximumRows, 0);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeOrObjects(int maximumRows, int startIndex)
        {
            return SearchLikeOrObjects(maximumRows, startIndex, null, false);
        }
        public List<Indico.BusinessObjects.UserHistoryBO> SearchLikeOrObjects(int maximumRows, int startIndex, string sortExpression, bool sortDescending)
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            IQueryable<Indico.DAL.UserHistory> oQuery =
                (from o in context.UserHistory
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    (this.User == 0 || this.User == o.User.ID) && 
                    (this.Company == 0 || this.Company == o.Company) && 
                    (this.DateCreated == null || this.DateCreated == o.DateCreated) && 
                    (this.Creator == 0 || this.Creator == o.Creator.ID) && 
                    (this.IsActive == false || this.IsActive == o.IsActive) && 
                    (this.IsDeleted == false || this.IsDeleted == o.IsDeleted) && 
                    ((o.Username.Contains(this.Username)) ||
                    (o.Password.Contains(this.Password)) ||
                    (o.GivenName.Contains(this.GivenName)) ||
                    (o.FamilyName.Contains(this.FamilyName)) ||
                    (o.EmailAddress.Contains(this.EmailAddress)) ||
                    (o.Guid.Contains(this.Guid)) ||
                    (this.Username == null && this.Password == null && this.GivenName == null && this.FamilyName == null && this.EmailAddress == null && this.Guid == null ))
                 orderby o.ID
                 select o);

            if (sortExpression != null && sortExpression.Length > 0)
            {
                // using System.Linq.Dynamic here in Dynamic.cs;
                if (sortDescending)
                    oQuery = oQuery.OrderBy(sortExpression + " desc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
                else
                    oQuery = oQuery.OrderBy(sortExpression + " asc").Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);
            }
            else
                oQuery = oQuery.OrderBy(obj => obj.ID).Skip(startIndex).Take((maximumRows == 0) ? Int32.MaxValue : maximumRows);

            List<Indico.BusinessObjects.UserHistoryBO> userhistorys = IQueryableToList(oQuery);
            if (this.Context == null)
            {
                context.Dispose();
            }
            
            return userhistorys;
        }
        
        public int SearchLikeOrObjectsCount()
        {
            IndicoEntities context = (this.Context != null) ? this.Context.Context : new IndicoEntities();
            return (from o in context.UserHistory
                 where
                    (this.ID == 0 || this.ID == o.ID) && 
                    (this.User == 0 || this.User == o.User.ID) && 
                    (this.Company == 0 || this.Company == o.Company) && 
                    (this.DateCreated == null || this.DateCreated == o.DateCreated) && 
                    (this.Creator == 0 || this.Creator == o.Creator.ID) && 
                    (this.IsActive == false || this.IsActive == o.IsActive) && 
                    (this.IsDeleted == false || this.IsDeleted == o.IsDeleted) && 
                    ((o.Username.Contains(this.Username)) ||
                    (o.Password.Contains(this.Password)) ||
                    (o.GivenName.Contains(this.GivenName)) ||
                    (o.FamilyName.Contains(this.FamilyName)) ||
                    (o.EmailAddress.Contains(this.EmailAddress)) ||
                    (o.Guid.Contains(this.Guid)) ||
                    (this.Username == null && this.Password == null && this.GivenName == null && this.FamilyName == null && this.EmailAddress == null && this.Guid == null ))
                 orderby o.ID
                 select o).Count();
            
        }
        #endregion
        
        #region Serialization methods
        /// <summary>
        /// Serializes the Indico.BusinessObjects.UserHistoryBO to an XML representation
        /// </summary>
        /// <returns>a XML string serialized representation</returns>
        public string SerializeObject()
        {
            string strReturn = "";

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();

            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            x.Serialize(objStream, this);

            System.Text.Encoding encoding = System.Text.Encoding.UTF8;
            // Read string from binary file with UTF8 encoding
            strReturn = encoding.GetString(objStream.GetBuffer());

            objStream.Close();
            return strReturn;

        }

        /// <summary>
        /// Deserializes Indico.BusinessObjects.UserHistoryBO object from an XML representation
        /// </summary>
        /// <param name="strXML">a XML string serialized representation</param>
        public Indico.BusinessObjects.UserHistoryBO DeserializeObject(string strXML)
        {
            Indico.BusinessObjects.UserHistoryBO objTemp = null;
            System.Xml.XmlDocument objXML = new System.Xml.XmlDocument();

            objXML.LoadXml(strXML);
            System.Text.Encoding encoding = System.Text.Encoding.UTF8;

            System.IO.MemoryStream objStream = new System.IO.MemoryStream();
            byte[] b = encoding.GetBytes(objXML.OuterXml);

            objStream.Write(b, 0, (int)b.Length);
            objStream.Position = 0;
            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(this.GetType());

            objTemp = (Indico.BusinessObjects.UserHistoryBO)x.Deserialize(objStream);
            objStream.Close();
            return objTemp;
        }

        /// <summary>
        /// Returns a simple XML representation of Indico.BusinessObjects.UserHistoryBO object in an XmlElement
        /// </summary>
        /// <returns>An XML snippet representing the object</returns>
        public string ToXmlString()
        {
            // MW TODO - implement this better.
            return SerializeObject();
        }
        #endregion
        
        #region OnPropertyChange Methods
        partial void OnIDChanged()
        {
            OnUserHistoryBOIDChanged();
        }
        
        partial void OnIDChanging(int value)
        {
            if (value < 0)
            {
                throw new Exception(String.Format("UserHistoryBO.ID must be more than or equal to 0. The supplied value was {0}.", value));
            }
            OnUserHistoryBOIDChanging(value);
        }
        partial void OnIDChanged();
        partial void OnIDChanging(int value);
        partial void OnUserHistoryBOIDChanged();
        partial void OnUserHistoryBOIDChanging(int value);
        
        partial void OnUserChanged()
        {
            OnUserHistoryBOUserChanged();
        }
        
        partial void OnUserChanging(int value)
        {
            if (value < 0)
            {
                throw new Exception(String.Format("UserHistoryBO.User must be more than or equal to 0. The supplied value was {0}.", value));
            }
            OnUserHistoryBOUserChanging(value);
        }
        partial void OnUserChanged();
        partial void OnUserChanging(int value);
        partial void OnUserHistoryBOUserChanged();
        partial void OnUserHistoryBOUserChanging(int value);
        
        partial void OnCompanyChanged()
        {
            OnUserHistoryBOCompanyChanged();
        }
        
        partial void OnCompanyChanging(int value)
        {
            OnUserHistoryBOCompanyChanging(value);
        }
        partial void OnCompanyChanged();
        partial void OnCompanyChanging(int value);
        partial void OnUserHistoryBOCompanyChanged();
        partial void OnUserHistoryBOCompanyChanging(int value);
        
        partial void OnUsernameChanged()
        {
            OnUserHistoryBOUsernameChanged();
        }
        
        partial void OnUsernameChanging(string value)
        {
            if (value != null && value.Length > 32)
            {
                throw new Exception(String.Format("UserHistoryBO.Username has a maximum length of 32. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnUserHistoryBOUsernameChanging(value);
        }
        partial void OnUsernameChanged();
        partial void OnUsernameChanging(string value);
        partial void OnUserHistoryBOUsernameChanged();
        partial void OnUserHistoryBOUsernameChanging(string value);
        
        partial void OnPasswordChanged()
        {
            OnUserHistoryBOPasswordChanged();
        }
        
        partial void OnPasswordChanging(string value)
        {
            if (value != null && value.Length > 255)
            {
                throw new Exception(String.Format("UserHistoryBO.Password has a maximum length of 255. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnUserHistoryBOPasswordChanging(value);
        }
        partial void OnPasswordChanged();
        partial void OnPasswordChanging(string value);
        partial void OnUserHistoryBOPasswordChanged();
        partial void OnUserHistoryBOPasswordChanging(string value);
        
        partial void OnGivenNameChanged()
        {
            OnUserHistoryBOGivenNameChanged();
        }
        
        partial void OnGivenNameChanging(string value)
        {
            if (value != null && value.Length > 32)
            {
                throw new Exception(String.Format("UserHistoryBO.GivenName has a maximum length of 32. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnUserHistoryBOGivenNameChanging(value);
        }
        partial void OnGivenNameChanged();
        partial void OnGivenNameChanging(string value);
        partial void OnUserHistoryBOGivenNameChanged();
        partial void OnUserHistoryBOGivenNameChanging(string value);
        
        partial void OnFamilyNameChanged()
        {
            OnUserHistoryBOFamilyNameChanged();
        }
        
        partial void OnFamilyNameChanging(string value)
        {
            if (value != null && value.Length > 32)
            {
                throw new Exception(String.Format("UserHistoryBO.FamilyName has a maximum length of 32. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnUserHistoryBOFamilyNameChanging(value);
        }
        partial void OnFamilyNameChanged();
        partial void OnFamilyNameChanging(string value);
        partial void OnUserHistoryBOFamilyNameChanged();
        partial void OnUserHistoryBOFamilyNameChanging(string value);
        
        partial void OnEmailAddressChanged()
        {
            OnUserHistoryBOEmailAddressChanged();
        }
        
        partial void OnEmailAddressChanging(string value)
        {
            if (value != null && value.Length > 64)
            {
                throw new Exception(String.Format("UserHistoryBO.EmailAddress has a maximum length of 64. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnUserHistoryBOEmailAddressChanging(value);
        }
        partial void OnEmailAddressChanged();
        partial void OnEmailAddressChanging(string value);
        partial void OnUserHistoryBOEmailAddressChanged();
        partial void OnUserHistoryBOEmailAddressChanging(string value);
        
        partial void OnDateCreatedChanged()
        {
            OnUserHistoryBODateCreatedChanged();
        }
        
        partial void OnDateCreatedChanging(DateTime? value)
        {
            OnUserHistoryBODateCreatedChanging(value);
        }
        partial void OnDateCreatedChanged();
        partial void OnDateCreatedChanging(DateTime? value);
        partial void OnUserHistoryBODateCreatedChanged();
        partial void OnUserHistoryBODateCreatedChanging(DateTime? value);
        
        partial void OnCreatorChanged()
        {
            OnUserHistoryBOCreatorChanged();
        }
        
        partial void OnCreatorChanging(int value)
        {
            if (value < 0)
            {
                throw new Exception(String.Format("UserHistoryBO.Creator must be more than or equal to 0. The supplied value was {0}.", value));
            }
            OnUserHistoryBOCreatorChanging(value);
        }
        partial void OnCreatorChanged();
        partial void OnCreatorChanging(int value);
        partial void OnUserHistoryBOCreatorChanged();
        partial void OnUserHistoryBOCreatorChanging(int value);
        
        partial void OnIsActiveChanged()
        {
            OnUserHistoryBOIsActiveChanged();
        }
        
        partial void OnIsActiveChanging(bool value)
        {
            OnUserHistoryBOIsActiveChanging(value);
        }
        partial void OnIsActiveChanged();
        partial void OnIsActiveChanging(bool value);
        partial void OnUserHistoryBOIsActiveChanged();
        partial void OnUserHistoryBOIsActiveChanging(bool value);
        
        partial void OnIsDeletedChanged()
        {
            OnUserHistoryBOIsDeletedChanged();
        }
        
        partial void OnIsDeletedChanging(bool value)
        {
            OnUserHistoryBOIsDeletedChanging(value);
        }
        partial void OnIsDeletedChanged();
        partial void OnIsDeletedChanging(bool value);
        partial void OnUserHistoryBOIsDeletedChanged();
        partial void OnUserHistoryBOIsDeletedChanging(bool value);
        
        partial void OnGuidChanged()
        {
            OnUserHistoryBOGuidChanged();
        }
        
        partial void OnGuidChanging(string value)
        {
            if (value != null && value.Length > 36)
            {
                throw new Exception(String.Format("UserHistoryBO.Guid has a maximum length of 36. The supplied value \"{0}\" has a length of {1}", value, value.Length));
            }
            OnUserHistoryBOGuidChanging(value);
        }
        partial void OnGuidChanged();
        partial void OnGuidChanging(string value);
        partial void OnUserHistoryBOGuidChanged();
        partial void OnUserHistoryBOGuidChanging(string value);
        
        #endregion
        
        #region IComparable Members

        public int CompareTo(object obj)
        {
            if (!(obj is Indico.BusinessObjects.UserHistoryBO))
                return 1;
            Indico.BusinessObjects.UserHistoryBOComparer c = new Indico.BusinessObjects.UserHistoryBOComparer();
            return c.Compare(this, obj as Indico.BusinessObjects.UserHistoryBO);
        }

        #endregion
        #endregion
        
        #region Events
        
        void obj_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == "ID")
            {
                // reload me
                this.SetBO((Indico.DAL.UserHistory)sender);
            }
        }
        
        void Context_OnSendBeforeChanges(object sender, EventArgs e)
        {        
        }
        
        void Context_OnSendAfterChanges(object sender, EventArgs e)
        {   
            if (this.ID > 0)
            {
                this.Cache();
            }
        }

        #endregion
    }
    
    #region UserHistoryBOComparer
    public class UserHistoryBOComparer : IComparer<Indico.BusinessObjects.UserHistoryBO>
    {
        private string propertyToCompareName;
        public UserHistoryBOComparer(string propertyToCompare)
        {
            PropertyInfo p = typeof(Indico.BusinessObjects.UserHistoryBO).GetProperty(propertyToCompare);
            if (p == null)
                throw new ArgumentException("is not a public property of Indico.BusinessObjects.UserHistoryBO", "propertyToCompare");
            this.propertyToCompareName = propertyToCompare;
        }
        
        public UserHistoryBOComparer()
        {
        
        }

        #region IComparer<Indico.BusinessObjects.UserHistoryBO> Members
        public int Compare(Indico.BusinessObjects.UserHistoryBO x, Indico.BusinessObjects.UserHistoryBO y)
        {
            if (propertyToCompareName != null)
            {
                PropertyInfo p = typeof(Indico.BusinessObjects.UserHistoryBO).GetProperty(propertyToCompareName);
                return compare(p, x, y);
            }
            else
            {
                PropertyInfo[] arrP = typeof(Indico.BusinessObjects.UserHistoryBO).GetProperties();
                foreach (PropertyInfo p in arrP)
                {
                    int v = compare(p, x, y);
                    if (v != 0)
                        return v;
                }
                return 0;
            }
        }

        private int compare(PropertyInfo p, Indico.BusinessObjects.UserHistoryBO x, Indico.BusinessObjects.UserHistoryBO y)
        {
            object xVal = p.GetValue(x, null);
            object yVal = p.GetValue(y, null);

            if (xVal == null)
            {
                if (yVal == null)
                    return 0;
                else
                    return -1; // x is null, y is not, y is greater
            }
            else
            {
                if (y == null)
                    return 1; // x non null, y is null, x is greater
                else if (xVal is string)
                {
                    return StringComparer.OrdinalIgnoreCase.Compare(xVal, yVal);
                }
                else if (xVal is IComparable)
                {
                    return ((IComparable)xVal).CompareTo((IComparable)yVal);
                }
                else
                    throw new ArgumentException
                        ("is not string or valuetype that implements IComparable", "propertyToCompare");

            }
        }

        #endregion
    }
    #endregion
}
