//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoryColor
    {
        public AccessoryColor()
        {
            this.ArtWorktAccessories = new HashSet<ArtWorktAccessory>();
            this.EmbroideryDetails = new HashSet<EmbroideryDetail>();
            this.FabricCodes = new HashSet<FabricCode>();
            this.VisualLayoutAccessories = new HashSet<VisualLayoutAccessory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ColorValue { get; set; }
    
        public virtual ICollection<ArtWorktAccessory> ArtWorktAccessories { get; set; }
        public virtual ICollection<EmbroideryDetail> EmbroideryDetails { get; set; }
        public virtual ICollection<FabricCode> FabricCodes { get; set; }
        public virtual ICollection<VisualLayoutAccessory> VisualLayoutAccessories { get; set; }
    }
}
