//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelPriceMarkup
    {
        public int ID { get; set; }
        public Nullable<int> Label { get; set; }
        public int PriceLevel { get; set; }
        public decimal Markup { get; set; }
    
        public virtual PriceMarkupLabel PriceMarkupLabel { get; set; }
        public virtual PriceLevel PriceLevel1 { get; set; }
    }
}
