//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnProductionCapacitiesView
    {
        public int Firms { get; set; }
        public int ResevationOrders { get; set; }
        public int Resevations { get; set; }
        public int Holds { get; set; }
        public int Less5Items { get; set; }
        public int Samples { get; set; }
    }
}
