//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDownloadPriceListView
    {
        public int Distributor { get; set; }
        public int Label { get; set; }
        public string Name { get; set; }
        public string PriceTerm { get; set; }
        public Nullable<bool> EditedPrice { get; set; }
        public decimal CreativeDesign { get; set; }
        public decimal StudioDesign { get; set; }
        public decimal ThirdPartyDesign { get; set; }
        public decimal Position1 { get; set; }
        public decimal Position2 { get; set; }
        public decimal Position3 { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
