//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisualLayoutAccessory
    {
        public int ID { get; set; }
        public int VisualLayout { get; set; }
        public Nullable<int> Accessory { get; set; }
        public Nullable<int> AccessoryColor { get; set; }
    
        public virtual Accessory Accessory1 { get; set; }
        public virtual AccessoryColor AccessoryColor1 { get; set; }
        public virtual VisualLayout VisualLayout1 { get; set; }
    }
}
